# Cleaning Data
v.ekc

Raw data is almost never ready to use. Today we clean the YouTube dataset from last week and learn to reshape wide/long data — two skills you'll use constantly in the wild.

| Section | Topic |
|---------|-------|
| 1 | Setup |
| 2 | Cleaning the Data |
| 3 | Reshaping Data |
| 4 | 🔬 Activity — Pets DataFrame |
| Appendix | Quick Reference |

---
## 1. Setup

In [66]:
import numpy as np
import pandas as pd

In [67]:
# import the youtube data from last time
df = pd.read_csv('humboldt_youtube_2025.csv', dtype={'viewCount': 'object', 'likeCount':'object'})
df.head()

,etag,kind,videoId,publishedAt,channelId,title,description,default_url,default_width,default_height,...,medium_width,medium_height,high_url,high_width,high_height,channelTitle,liveBroadcastContent,publishTime,viewCount,likeCount
0,sQ5NDeYAHpbNJOKc7krGKs9IP3k,youtube#video,PoGnLtH1UHY,2025-04-01T17:26:59Z,UCg7Fdhrmwi8ZqakqiO3xPkg,Trio at Cal Poly Humboldt,"""We're here to support people, meet you where ...",https://i.ytimg.com/vi/PoGnLtH1UHY/default.jpg,120,90,...,320,180,https://i.ytimg.com/vi/PoGnLtH1UHY/hqdefault.jpg,480,360,HumboldtOnline,none,2025-04-01T17:26:59Z,27,2
1,8frtqOI_0dcOCINsANaOhri0fTk,youtube#video,u-PfB0FTmxI,2025-02-01T00:32:55Z,UCg7Fdhrmwi8ZqakqiO3xPkg,SOUNDCHECK: &quot;Yes or No&quot; - Cal Poly H...,"Yes or No” by Wayne Shorter, performed at soun...",https://i.ytimg.com/vi/u-PfB0FTmxI/default.jpg,120,90,...,320,180,https://i.ytimg.com/vi/u-PfB0FTmxI/hqdefault.jpg,480,360,HumboldtOnline,none,2025-02-01T00:32:55Z,164,20
2,_uQQJvfoAz7qZJYaOYyp0YEpkpU,youtube#video,90yFl295N9M,2024-12-21T04:43:58Z,UCg7Fdhrmwi8ZqakqiO3xPkg,Fall Commencement 2024,Congratulations to the Cal Poly Humboldt gradu...,https://i.ytimg.com/vi/90yFl295N9M/default.jpg,120,90,...,320,180,https://i.ytimg.com/vi/90yFl295N9M/hqdefault.jpg,480,360,HumboldtOnline,none,2024-12-21T04:43:58Z,90,4
3,FuC2K8Hl9XO9hcVRF0AAVqn_8fM,youtube#video,FTrKunStGOg,2024-12-11T20:29:04Z,UCg7Fdhrmwi8ZqakqiO3xPkg,Happy Holidays From Cal Poly Humboldt,"As we look ahead to the new year, students get...",https://i.ytimg.com/vi/FTrKunStGOg/default.jpg,120,90,...,320,180,https://i.ytimg.com/vi/FTrKunStGOg/hqdefault.jpg,480,360,HumboldtOnline,none,2024-12-11T20:29:04Z,2211,79
4,dz5BcVshPQtrCKBA_YUAcnfoqXU,youtube#video,Wkbj2V8CQTw,2024-10-17T23:08:59Z,UCg7Fdhrmwi8ZqakqiO3xPkg,Groundbreaking: Engineering &amp; Technology B...,Ushering in a new era for Northern California'...,https://i.ytimg.com/vi/Wkbj2V8CQTw/default.jpg,120,90,...,320,180,https://i.ytimg.com/vi/Wkbj2V8CQTw/hqdefault.jpg,480,360,HumboldtOnline,none,2024-10-17T23:08:59Z,355,5

In [68]:
df.shape

(50, 21)

---
## 2. Cleaning the Data

We'll work through four common cleaning steps: fixing column names, correcting data types, setting the index, and reordering.

### References

| Task | Code | Notes |
|------|------|-------|
| Rename specific columns | `df.rename(columns={'old':'new'})` | Returns new df unless `inplace=True` |
| Rename all columns | `df.columns = [...]` | Replaces all names at once |
| Drop column | `df.drop(columns='col', inplace=True)` | |
| Remove constant columns | `df.loc[:, df.nunique() > 1]` | Keep only columns with >1 unique value |
| Convert type | `df.astype({'col': int})` | |
| Parse datetime | `pd.to_datetime(df['col'])` | Use `format=` for non-standard strings |
| Set index | `df.set_index('col', inplace=True)` | |
| Sort rows | `df.sort_values(by='col', ascending=False)` | |
| Sort columns | `df.sort_index(axis=1)` | |

### Column Names

In [69]:
# Check the column names
df.columns

Index(['etag', 'kind', 'videoId', 'publishedAt', 'channelId', 'title',
       'description', 'default_url', 'default_width', 'default_height',
       'medium_url', 'medium_width', 'medium_height', 'high_url', 'high_width',
       'high_height', 'channelTitle', 'liveBroadcastContent', 'publishTime',
       'viewCount', 'likeCount'],
      dtype='str')

In [70]:
# Inspect some questions
#   is published at and publish time the same?

sum(df.publishedAt != df.publishTime)

0

In [71]:
# the two columns above are identical
# Remember how to drop a column???
#    let's drop 'publishTime'

In [72]:
# Check for any columns with just one value
(df.nunique() == 1)

etag                    False
kind                     True
videoId                 False
publishedAt             False
channelId                True
title                   False
description             False
default_url             False
default_width            True
default_height           True
medium_url              False
medium_width             True
medium_height            True
high_url                False
high_width               True
high_height              True
channelTitle             True
liveBroadcastContent     True
publishTime             False
viewCount               False
likeCount               False
dtype: bool

In [73]:
# Save some relevant data, then remove redundant columns
channel_id = df.channelId[0]
chanel_title = df.channelTitle[0]

In [74]:
df = df.loc[:,df.nunique() > 1]

In [75]:
df.head()

,etag,videoId,publishedAt,title,description,default_url,medium_url,high_url,publishTime,viewCount,likeCount
0,sQ5NDeYAHpbNJOKc7krGKs9IP3k,PoGnLtH1UHY,2025-04-01T17:26:59Z,Trio at Cal Poly Humboldt,"""We're here to support people, meet you where ...",https://i.ytimg.com/vi/PoGnLtH1UHY/default.jpg,https://i.ytimg.com/vi/PoGnLtH1UHY/mqdefault.jpg,https://i.ytimg.com/vi/PoGnLtH1UHY/hqdefault.jpg,2025-04-01T17:26:59Z,27,2
1,8frtqOI_0dcOCINsANaOhri0fTk,u-PfB0FTmxI,2025-02-01T00:32:55Z,SOUNDCHECK: &quot;Yes or No&quot; - Cal Poly H...,"Yes or No” by Wayne Shorter, performed at soun...",https://i.ytimg.com/vi/u-PfB0FTmxI/default.jpg,https://i.ytimg.com/vi/u-PfB0FTmxI/mqdefault.jpg,https://i.ytimg.com/vi/u-PfB0FTmxI/hqdefault.jpg,2025-02-01T00:32:55Z,164,20
2,_uQQJvfoAz7qZJYaOYyp0YEpkpU,90yFl295N9M,2024-12-21T04:43:58Z,Fall Commencement 2024,Congratulations to the Cal Poly Humboldt gradu...,https://i.ytimg.com/vi/90yFl295N9M/default.jpg,https://i.ytimg.com/vi/90yFl295N9M/mqdefault.jpg,https://i.ytimg.com/vi/90yFl295N9M/hqdefault.jpg,2024-12-21T04:43:58Z,90,4
3,FuC2K8Hl9XO9hcVRF0AAVqn_8fM,FTrKunStGOg,2024-12-11T20:29:04Z,Happy Holidays From Cal Poly Humboldt,"As we look ahead to the new year, students get...",https://i.ytimg.com/vi/FTrKunStGOg/default.jpg,https://i.ytimg.com/vi/FTrKunStGOg/mqdefault.jpg,https://i.ytimg.com/vi/FTrKunStGOg/hqdefault.jpg,2024-12-11T20:29:04Z,2211,79
4,dz5BcVshPQtrCKBA_YUAcnfoqXU,Wkbj2V8CQTw,2024-10-17T23:08:59Z,Groundbreaking: Engineering &amp; Technology B...,Ushering in a new era for Northern California'...,https://i.ytimg.com/vi/Wkbj2V8CQTw/default.jpg,https://i.ytimg.com/vi/Wkbj2V8CQTw/mqdefault.jpg,https://i.ytimg.com/vi/Wkbj2V8CQTw/hqdefault.jpg,2024-10-17T23:08:59Z,355,5

Our column names are in different formats — let's standardize them.

In [76]:
# OPTION 1 .rename method
df.rename(columns = {'videoId':'video_id',
                     'publishedAt':'published_at',
                     'viewCount':'view_count',
                     'likeCount':'like_count'}).head()

,etag,video_id,published_at,title,description,default_url,medium_url,high_url,publishTime,view_count,like_count
0,sQ5NDeYAHpbNJOKc7krGKs9IP3k,PoGnLtH1UHY,2025-04-01T17:26:59Z,Trio at Cal Poly Humboldt,"""We're here to support people, meet you where ...",https://i.ytimg.com/vi/PoGnLtH1UHY/default.jpg,https://i.ytimg.com/vi/PoGnLtH1UHY/mqdefault.jpg,https://i.ytimg.com/vi/PoGnLtH1UHY/hqdefault.jpg,2025-04-01T17:26:59Z,27,2
1,8frtqOI_0dcOCINsANaOhri0fTk,u-PfB0FTmxI,2025-02-01T00:32:55Z,SOUNDCHECK: &quot;Yes or No&quot; - Cal Poly H...,"Yes or No” by Wayne Shorter, performed at soun...",https://i.ytimg.com/vi/u-PfB0FTmxI/default.jpg,https://i.ytimg.com/vi/u-PfB0FTmxI/mqdefault.jpg,https://i.ytimg.com/vi/u-PfB0FTmxI/hqdefault.jpg,2025-02-01T00:32:55Z,164,20
2,_uQQJvfoAz7qZJYaOYyp0YEpkpU,90yFl295N9M,2024-12-21T04:43:58Z,Fall Commencement 2024,Congratulations to the Cal Poly Humboldt gradu...,https://i.ytimg.com/vi/90yFl295N9M/default.jpg,https://i.ytimg.com/vi/90yFl295N9M/mqdefault.jpg,https://i.ytimg.com/vi/90yFl295N9M/hqdefault.jpg,2024-12-21T04:43:58Z,90,4
3,FuC2K8Hl9XO9hcVRF0AAVqn_8fM,FTrKunStGOg,2024-12-11T20:29:04Z,Happy Holidays From Cal Poly Humboldt,"As we look ahead to the new year, students get...",https://i.ytimg.com/vi/FTrKunStGOg/default.jpg,https://i.ytimg.com/vi/FTrKunStGOg/mqdefault.jpg,https://i.ytimg.com/vi/FTrKunStGOg/hqdefault.jpg,2024-12-11T20:29:04Z,2211,79
4,dz5BcVshPQtrCKBA_YUAcnfoqXU,Wkbj2V8CQTw,2024-10-17T23:08:59Z,Groundbreaking: Engineering &amp; Technology B...,Ushering in a new era for Northern California'...,https://i.ytimg.com/vi/Wkbj2V8CQTw/default.jpg,https://i.ytimg.com/vi/Wkbj2V8CQTw/mqdefault.jpg,https://i.ytimg.com/vi/Wkbj2V8CQTw/hqdefault.jpg,2024-10-17T23:08:59Z,355,5

In [77]:
# does not update original (use inline=True)
df.head()

,etag,videoId,publishedAt,title,description,default_url,medium_url,high_url,publishTime,viewCount,likeCount
0,sQ5NDeYAHpbNJOKc7krGKs9IP3k,PoGnLtH1UHY,2025-04-01T17:26:59Z,Trio at Cal Poly Humboldt,"""We're here to support people, meet you where ...",https://i.ytimg.com/vi/PoGnLtH1UHY/default.jpg,https://i.ytimg.com/vi/PoGnLtH1UHY/mqdefault.jpg,https://i.ytimg.com/vi/PoGnLtH1UHY/hqdefault.jpg,2025-04-01T17:26:59Z,27,2
1,8frtqOI_0dcOCINsANaOhri0fTk,u-PfB0FTmxI,2025-02-01T00:32:55Z,SOUNDCHECK: &quot;Yes or No&quot; - Cal Poly H...,"Yes or No” by Wayne Shorter, performed at soun...",https://i.ytimg.com/vi/u-PfB0FTmxI/default.jpg,https://i.ytimg.com/vi/u-PfB0FTmxI/mqdefault.jpg,https://i.ytimg.com/vi/u-PfB0FTmxI/hqdefault.jpg,2025-02-01T00:32:55Z,164,20
2,_uQQJvfoAz7qZJYaOYyp0YEpkpU,90yFl295N9M,2024-12-21T04:43:58Z,Fall Commencement 2024,Congratulations to the Cal Poly Humboldt gradu...,https://i.ytimg.com/vi/90yFl295N9M/default.jpg,https://i.ytimg.com/vi/90yFl295N9M/mqdefault.jpg,https://i.ytimg.com/vi/90yFl295N9M/hqdefault.jpg,2024-12-21T04:43:58Z,90,4
3,FuC2K8Hl9XO9hcVRF0AAVqn_8fM,FTrKunStGOg,2024-12-11T20:29:04Z,Happy Holidays From Cal Poly Humboldt,"As we look ahead to the new year, students get...",https://i.ytimg.com/vi/FTrKunStGOg/default.jpg,https://i.ytimg.com/vi/FTrKunStGOg/mqdefault.jpg,https://i.ytimg.com/vi/FTrKunStGOg/hqdefault.jpg,2024-12-11T20:29:04Z,2211,79
4,dz5BcVshPQtrCKBA_YUAcnfoqXU,Wkbj2V8CQTw,2024-10-17T23:08:59Z,Groundbreaking: Engineering &amp; Technology B...,Ushering in a new era for Northern California'...,https://i.ytimg.com/vi/Wkbj2V8CQTw/default.jpg,https://i.ytimg.com/vi/Wkbj2V8CQTw/mqdefault.jpg,https://i.ytimg.com/vi/Wkbj2V8CQTw/hqdefault.jpg,2024-10-17T23:08:59Z,355,5

In [78]:
# OPTION 2: more general approach that would work for many columns
# Split column names by words
import re
split_by_words = [re.split('(?=[A-Z])',i) for i in df.columns]
split_by_words

[['etag'],
 ['video', 'Id'],
 ['published', 'At'],
 ['title'],
 ['description'],
 ['default_url'],
 ['medium_url'],
 ['high_url'],
 ['publish', 'Time'],
 ['view', 'Count'],
 ['like', 'Count']]

In [79]:
# Insert an underscore between words
columns_with_underscores = ['_'.join(i).lower() for i in split_by_words]
columns_with_underscores

['etag',
 'video_id',
 'published_at',
 'title',
 'description',
 'default_url',
 'medium_url',
 'high_url',
 'publish_time',
 'view_count',
 'like_count']

In [80]:
# Reassign column names
df.columns = columns_with_underscores

In [81]:
df.head()

,etag,video_id,published_at,title,description,default_url,medium_url,high_url,publish_time,view_count,like_count
0,sQ5NDeYAHpbNJOKc7krGKs9IP3k,PoGnLtH1UHY,2025-04-01T17:26:59Z,Trio at Cal Poly Humboldt,"""We're here to support people, meet you where ...",https://i.ytimg.com/vi/PoGnLtH1UHY/default.jpg,https://i.ytimg.com/vi/PoGnLtH1UHY/mqdefault.jpg,https://i.ytimg.com/vi/PoGnLtH1UHY/hqdefault.jpg,2025-04-01T17:26:59Z,27,2
1,8frtqOI_0dcOCINsANaOhri0fTk,u-PfB0FTmxI,2025-02-01T00:32:55Z,SOUNDCHECK: &quot;Yes or No&quot; - Cal Poly H...,"Yes or No” by Wayne Shorter, performed at soun...",https://i.ytimg.com/vi/u-PfB0FTmxI/default.jpg,https://i.ytimg.com/vi/u-PfB0FTmxI/mqdefault.jpg,https://i.ytimg.com/vi/u-PfB0FTmxI/hqdefault.jpg,2025-02-01T00:32:55Z,164,20
2,_uQQJvfoAz7qZJYaOYyp0YEpkpU,90yFl295N9M,2024-12-21T04:43:58Z,Fall Commencement 2024,Congratulations to the Cal Poly Humboldt gradu...,https://i.ytimg.com/vi/90yFl295N9M/default.jpg,https://i.ytimg.com/vi/90yFl295N9M/mqdefault.jpg,https://i.ytimg.com/vi/90yFl295N9M/hqdefault.jpg,2024-12-21T04:43:58Z,90,4
3,FuC2K8Hl9XO9hcVRF0AAVqn_8fM,FTrKunStGOg,2024-12-11T20:29:04Z,Happy Holidays From Cal Poly Humboldt,"As we look ahead to the new year, students get...",https://i.ytimg.com/vi/FTrKunStGOg/default.jpg,https://i.ytimg.com/vi/FTrKunStGOg/mqdefault.jpg,https://i.ytimg.com/vi/FTrKunStGOg/hqdefault.jpg,2024-12-11T20:29:04Z,2211,79
4,dz5BcVshPQtrCKBA_YUAcnfoqXU,Wkbj2V8CQTw,2024-10-17T23:08:59Z,Groundbreaking: Engineering &amp; Technology B...,Ushering in a new era for Northern California'...,https://i.ytimg.com/vi/Wkbj2V8CQTw/default.jpg,https://i.ytimg.com/vi/Wkbj2V8CQTw/mqdefault.jpg,https://i.ytimg.com/vi/Wkbj2V8CQTw/hqdefault.jpg,2024-10-17T23:08:59Z,355,5

### Convert Datatypes

In [82]:
# Suppose we wanted to look at the relationship between view counts and like counts
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('darkgrid')

# plot a scatter with x=view_count, y=like_count

#### check

sns.scatterplot(data = df, x='view_count',y='like_count')
plt.show()

sns.relplot(data=df,
          x='view_count',
          y='like_count')

### We should have checked the dtypes!

In [83]:
# Something is funky. Check the data types
df.dtypes

etag               str
video_id           str
published_at       str
title              str
description        str
default_url        str
medium_url         str
high_url           str
publish_time       str
view_count      object
like_count      object
dtype: object

In [84]:
# convert the data types
df = df.astype({'view_count':int, 'like_count':int})

In [85]:
# check data types again
df.dtypes

etag              str
video_id          str
published_at      str
title             str
description       str
default_url       str
medium_url        str
high_url          str
publish_time      str
view_count      int64
like_count      int64
dtype: object

In [86]:
# plot again!

sns.
    
plt.show()

SyntaxError: invalid syntax (1263180548.py, line 3)

In [ ]:
# What if we wanted to plot trend in view counts?
#    x = published_at
#    y = view_count

sns.
plt.show()

#### check

In [ ]:
sns.relplot(data = df,
                x='published_at',
                y='view_count',
               kind='line')
plt.show()

### change dtypes again!

In [ ]:
# change dates to datetime data
df['published_at'] = pd.to_datetime(df.published_at)
df.head()

In [ ]:
# Check dtypes again
df.dtypes

In [ ]:
# plot again
plt.figure(figsize = (10,4))
sns.lineplot(data = df, x='published_at',y='view_count')
plt.show()

### Pandas datetime types can be interpreted in multiple formats:
### `pd.to_datetime(date1, format = 'format string from below list')`

| String | Format string |
|--------|--------------|
| `'April 5, 2025'` | `'%B %d, %Y'` |
| `'Apr 5, 2025'` | `'%b %d, %Y'` |
| `'4/5/25'` | `'%m/%d/%y'` |
| `'5-4-25'` | `'%d-%m-%y'` |
| `'4-5-2025'` | `'%m-%d-%Y'` |

You use the code `pd.to_datetime(date1, format = 'format string from above list')`

#### Examples

In [ ]:
date1 = 'April 5, 2025'
pd.to_datetime(date1, format = '%B %d, %Y')

In [ ]:
date2 = 'Apr 5, 2025'
pd.to_datetime(date2, format = '%b %d, %Y')

In [ ]:
date3 = '4/5/25'
pd.to_datetime(date3, format = '%m/%d/%y')

In [ ]:
date4 = '5-4-25'
pd.to_datetime(date4, format = '%d-%m-%y')

In [ ]:
date5 = '4-5-2025'
pd.to_datetime(date5, format = '%m-%d-%Y')

In [ ]:
date6 = '4-05-2025'
pd.to_datetime(date5, format = '%m-%d-%Y')

Use [this reference](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior) for more info about datetime formats.

### Reset the Index

In [ ]:
# Reset the index for easy access by video id
df.set_index('video_id',inplace=True)
df.head()

In [ ]:
# index by video id
video_id = "PoGnLtH1UHY"

......

In [ ]:
# get the info on the video with the highest view count!

...
????...

In [ ]:
#### check

# info on one video
video_id = "PoGnLtH1UHY"
df.loc[video_id]

# info on max watched video!
df.loc[df.view_count.idxmax()]

### Reorder the Data

In [ ]:
# reorder rows
df.sort_index(axis=0).head()


### Question: does this update the original????

In [ ]:
# doesn't update original
df.head()

In [ ]:
# reorder columns with axis=1
df.sort_index(axis=1).head()

In [ ]:
# Place columns in your chosen order
df[['view_count','like_count','published_at','title']].head()

In [ ]:
# sort the data 
df.sort_values(by='view_count').head()

In [ ]:
# doesn't update original
df.head()

In [ ]:
# do it inplace
df.sort_values(by = 'view_count',ascending=False, inplace=True)

In [ ]:
df.head()

In [ ]:
# sort by multiple values at once
df.sort_values(by = ['view_count','like_count'],ascending=[False,True], inplace=True)
df.head()

---
## 3. Reshaping Data

Data often arrives in the wrong shape for the analysis you want. Two transformations come up constantly: **wide → long** and **long → wide**. We'll build up each one step by step using weather data — then you'll practice on your own.

### References

| Direction | Function | When to use |
|-----------|----------|--------------|
| Wide → Long | `.melt(id_vars=, value_vars=)` | Each measurement → its own row |
| Wide → Long | `.stack()` | Column names become a new index level |
| Long → Wide | `.pivot(index=, columns=, values=)` | One value per cell — no aggregation |
| Long → Wide | `.pivot_table(aggfunc=)` | Multiple values per cell — aggregate them |

### Wide → Long

The weather dataset has one column per variable — let's collapse it so each row is a single measurement.

In [103]:
df_weather_wide = pd.read_csv('sample_weather.csv')
df_weather_wide = df_weather_wide.iloc[:,1:]
df_weather_wide

         date  inches_of_rain  max_temp  min_temp
0  2024-01-01             0.5        60        40
1  2024-01-02             0.0        55        45
2  2024-01-03             0.1        52        42
3  2022-01-04             0.0        56        48

In [104]:
# METHOD 1

# transpose with more informative columns
date_index = df_weather_wide.set_index('date')
date_index

            inches_of_rain  max_temp  min_temp
date
2024-01-01             0.5        60        40
2024-01-02             0.0        55        45
2024-01-03             0.1        52        42
2022-01-04             0.0        56        48

In [105]:
# Make a long Series
#   the result is a multi-indexed Series
#   level 0 index   |   level 1 index   |   value
#   dates, set index|   column names    |   cell values


long_df = date_index.stack()
long_df

date
2024-01-01  inches_of_rain     0.5
            max_temp          60.0
            min_temp          40.0
2024-01-02  inches_of_rain     0.0
            max_temp          55.0
            min_temp          45.0
2024-01-03  inches_of_rain     0.1
            max_temp          52.0
            min_temp          42.0
2022-01-04  inches_of_rain     0.0
            max_temp          56.0
            min_temp          48.0
dtype: float64

In [108]:
# now we get rid of the double indexing
#    we reset the index

long_df = long_df.reset_index(name='value')
long_df

# and then we will rename that column from level_1 ---> variable
#long_df.rename(columns = {'level_1':'variable'},inplace=True)

          date         level_1  value
0   2024-01-01  inches_of_rain    0.5
1   2024-01-01        max_temp   60.0
2   2024-01-01        min_temp   40.0
3   2024-01-02  inches_of_rain    0.0
4   2024-01-02        max_temp   55.0
5   2024-01-02        min_temp   45.0
6   2024-01-03  inches_of_rain    0.1
7   2024-01-03        max_temp   52.0
8   2024-01-03        min_temp   42.0
9   2022-01-04  inches_of_rain    0.0
10  2022-01-04        max_temp   56.0
11  2022-01-04        min_temp   48.0

In [112]:
# Method 1.5: a shortcut 
#   we pre-name the second index lol and then we don't have to rename it later

date_index.columns.name = 'variable'
date_index

variable    inches_of_rain  max_temp  min_temp
date
2024-01-01             0.5        60        40
2024-01-02             0.0        55        45
2024-01-03             0.1        52        42
2022-01-04             0.0        56        48

In [94]:
# Now renaming isn't necessary
date_index.stack().reset_index(name = 'value')

          date        variable  value
0   2024-01-01  inches_of_rain    0.5
1   2024-01-01        max_temp   60.0
2   2024-01-01        min_temp   40.0
3   2024-01-02  inches_of_rain    0.0
4   2024-01-02        max_temp   55.0
5   2024-01-02        min_temp   45.0
6   2024-01-03  inches_of_rain    0.1
7   2024-01-03        max_temp   52.0
8   2024-01-03        min_temp   42.0
9   2022-01-04  inches_of_rain    0.0
10  2022-01-04        max_temp   56.0
11  2022-01-04        min_temp   48.0

### The Two methods, `df.stack()` and `df.melt()`

Both methods get you to the same place. Here's the full step-by-step for each:

---

**`df.stack()`** *(3–4 steps)*

| Step | Code | What it does |
|------|------|--------------|
| 1 | `df.set_index('date')` | Move the ID column into the index so only the *data* columns remain |
| 2 | `.stack()` | Collapse all remaining columns into rows — column names become a new index level |
| 3 | `.reset_index(name='value')` | Flatten the MultiIndex back to regular columns; `name=` sets the values column label |
| 4 | `.rename(columns={'level_1': 'variable'})` | Give the auto-generated `level_1` column a meaningful name |

> **Shortcut for step 4:** Set `df.columns.name = 'variable'` *before* stacking — then the level is already named and `.rename()` isn't needed.

---

**`df.melt()`** *(1 step)*

| Argument | Role | Example |
|----------|------|---------|
| `id_vars=` | Column(s) that stay as row identifiers — repeated for every melted variable | `'date'` |
| `value_vars=` | Columns to collapse into rows — their names become the `variable` column | `['max_temp', 'min_temp', 'inches_of_rain']` |

```python

date    max_temp  min_temp  inches_of_rain
↑           ↑        ↑            ↑
id_vars  ←————————— value_vars ————————→    # the values of each cell become a new column called 'value'
```


`df_weather_wide.melt(id_vars='date', value_vars=['max_temp', 'min_temp', 'inches_of_rain'])`

```python
date  |  variable       |  value
——————————————————————————————————
id_vars  |  col names      |  cell values
         |  from           |  from
         |  value_vars     |  value_vars

```

> **When to use which:**
> Use `.melt()` when you know your column names and want clean, readable code.
> Use `.stack()` when you want to collapse *all* columns at once, or when working with a MultiIndex.

In [113]:
# METHOD 2

long_df = df_weather_wide.melt(id_vars = 'date',value_vars = ['max_temp','min_temp','inches_of_rain'])
long_df

          date        variable  value
0   2024-01-01        max_temp   60.0
1   2024-01-02        max_temp   55.0
2   2024-01-03        max_temp   52.0
3   2022-01-04        max_temp   56.0
4   2024-01-01        min_temp   40.0
5   2024-01-02        min_temp   45.0
6   2024-01-03        min_temp   42.0
7   2022-01-04        min_temp   48.0
8   2024-01-01  inches_of_rain    0.5
9   2024-01-02  inches_of_rain    0.0
10  2024-01-03  inches_of_rain    0.1
11  2022-01-04  inches_of_rain    0.0

---
### Try It 1: Wide → Long 😊

1. Use `.melt()` on `df_weather_wide`, but only include `max_temp` and `min_temp` (leave out `inches_of_rain`). What changes in the output compared to the full melt above?

2. After melting, rename the `variable` column to `weather_metric` and `value` to `measurement` using `.rename()`. Practice chaining your cleaning steps — melt, then rename.

In [ ]:
# 1. Use .melt() — but only keep 'max_temp' and 'min_temp'

In [ ]:
# 2. Rename the 'variable' and 'value' columns to something more descriptive

<details>
<summary>💡 Possible answers — click to peek</summary>
<br>

*Limiting `value_vars` is a quick way to melt only the columns you care about — great for dropping irrelevant variables before reshaping.*

```python
# 1. melt with only 2 variables
df_weather_wide.melt(id_vars='date', value_vars=['max_temp', 'min_temp'])
# result has fewer rows — one per date per included variable

# 2. rename after melting
(
    df_weather_wide
    .melt(id_vars='date', value_vars=['max_temp', 'min_temp'])
    .rename(columns={'variable': 'weather_metric', 'value': 'measurement'})
)
```

</details>

### Long → Wide

Now let's go the other direction. `.pivot()` works great when there's exactly **one value per (index, column) pair** — but real data often has duplicates. Let's see what happens.

In [97]:
# change long format back into wide format
long_df.pivot(index = 'date',columns = 'variable',values='value')

variable    inches_of_rain  max_temp  min_temp
date
2022-01-04             0.0      56.0      48.0
2024-01-01             0.5      60.0      40.0
2024-01-02             0.0      55.0      45.0
2024-01-03             0.1      52.0      42.0

In [98]:
long_df = pd.read_csv('long_data.csv')
long_df = long_df.iloc[:,1:]
long_df.head()

         date   product     category  sales
0  2024-03-02  ProductB     Clothing    561
1  2024-03-06  ProductA     Clothing    521
2  2024-03-03  ProductA        Books    120
3  2024-03-07  ProductA  Electronics    201
4  2024-03-05  ProductA        Books    527

In [99]:
# Pivot the data to get average sales by date and category
long_df.pivot_table(index=['date'], columns='category', values=['sales'])

                 sales
category         Books    Clothing Electronics
date
2024-03-01  738.333333  881.500000  750.000000
2024-03-02  599.833333  446.857143  700.333333
2024-03-03  447.875000  739.250000  576.375000
2024-03-04  753.000000  225.000000  791.000000
2024-03-05  706.250000  705.000000  519.166667
2024-03-06  445.000000  512.500000  317.500000
2024-03-07  398.500000  711.500000  389.500000
2024-03-08  498.666667  639.500000  534.833333
2024-03-09  819.000000  623.000000         NaN
2024-03-10         NaN  399.250000  438.250000

In [100]:
# Pivot the data to get TOTAL sales by date and category
wide_df = long_df.pivot_table(index=['date'], columns='category', values=['sales'], aggfunc=sum)
wide_df

             sales
category     Books Clothing Electronics
date
2024-03-01  2215.0   1763.0       750.0
2024-03-02  3599.0   3128.0      2101.0
2024-03-03  3583.0   2957.0      4611.0
2024-03-04   753.0    450.0      1582.0
2024-03-05  2825.0   2115.0      3115.0
2024-03-06  1780.0   1025.0      1270.0
2024-03-07   797.0   1423.0       779.0
2024-03-08  1496.0   1279.0      3209.0
2024-03-09   819.0   2492.0         NaN
2024-03-10     NaN   1597.0      1753.0

In [101]:
# Pivot the data to get TOTAL sales by date, product, and category
long_df.pivot_table(index='date', columns=['category','product'], values=['sales'], aggfunc=sum)

              sales                                                           \
category      Books                   Clothing                   Electronics
product    ProductA ProductB ProductC ProductA ProductB ProductC    ProductA
date
2024-03-01    617.0    877.0    721.0   1763.0      NaN      NaN         NaN
2024-03-02   1524.0    914.0   1161.0   1220.0    561.0   1347.0       953.0
2024-03-03   1649.0      NaN   1934.0    778.0   1574.0    605.0      1463.0
2024-03-04      NaN      NaN    753.0      NaN      NaN    450.0         NaN
2024-03-05    527.0    813.0   1485.0   2115.0      NaN      NaN      1297.0
2024-03-06    523.0    267.0    990.0    521.0    504.0      NaN       260.0
2024-03-07      NaN    797.0      NaN    683.0      NaN    740.0       201.0
2024-03-08      NaN   1333.0    163.0      NaN      NaN   1279.0       805.0
2024-03-09    819.0      NaN      NaN   1578.0      NaN    914.0         NaN
2024-03-10      NaN      NaN      NaN    312.0    540.0    745.0       630.0


category
product    ProductB ProductC
date
2024-03-01      NaN    750.0
2024-03-02    209.0    939.0
2024-03-03   1854.0   1294.0
2024-03-04    839.0    743.0
2024-03-05   1099.0    719.0
2024-03-06    162.0    848.0
2024-03-07    578.0      NaN
2024-03-08   1581.0    823.0
2024-03-09      NaN      NaN
2024-03-10    306.0    817.0

In [102]:
# Go from wide to long
wide_df.reset_index().melt(id_vars='date', var_name=['type','category'])

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['date']"

---
### 🔍 Identify It — Wide or Long?

Before you write any code, look at each DataFrame below and answer two things:
- Is it **wide** or **long** format?
- What arguments would you need to convert it to the **other** format?

Write your answers in the cells below each DataFrame. Then check the toggle when you're ready.

In [ ]:
# DataFrame A
df_a = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Carol'],
    'math':    [90, 78, 95],
    'science': [85, 88, 91],
    'english': [92, 75, 88]
})
df_a

**DataFrame A** — start here.

1. Is this **wide** or **long** format?
2. What `.melt()` arguments would you use to convert it to the other format?
   - `id_vars =` ?
   - `value_vars =` ?

**DataFrame A answers:**

- Format (wide or long?): *your answer*
- `id_vars =` *?*
- `value_vars =` *?*

In [ ]:
# DataFrame B
df_b = pd.DataFrame({
    'city':    ['SF', 'SF', 'LA', 'LA'],
    'drink':   ['latte', 'mocha', 'latte', 'mocha'],
    'revenue': [400, 250, 350, 300]
})
df_b

**DataFrame B** — now the other direction.

1. Is this **wide** or **long** format?
2. What function would you use to go the other way — `.pivot()` or `.pivot_table()`? Why?
3. What would `index`, `columns`, and `values` be?

**DataFrame B answers:**

- Format (wide or long?): *your answer*
- Can you use `.pivot()` or do you need `.pivot_table()`? *your answer*
- `index =` *?*
- `columns =` *?*
- `values =` *?*

In [ ]:
# DataFrame C
df_c = pd.DataFrame({
    'city':  ['SF','SF','SF','LA','LA','LA'],
    'drink': ['latte','latte','mocha','latte','mocha','mocha'],
    'revenue': [400, 220, 250, 350, 300, 175]
})
df_c

**DataFrame C** — Look carefully before you answer 👀

1. Is this **wide** or **long** format?
2. Can you use `.pivot()` to go wide? *Check the data first.*
3. What arguments would you pass to `.pivot_table()` to get total revenue by city and drink?

> *Hint: scan the city/drink combos — do any repeat?*

**DataFrame C answers:**

- Format (wide or long?): *your answer*
- Can you use `.pivot()` here? Why or why not? *your answer*
- `index =` *?*
- `columns =` *?*
- `values =` *?*
- `aggfunc =` *?*

<details>
<summary>💡 Answers — click to peek</summary>
<br>

*The key question for long→wide is always: "is there exactly one value per (index, column) pair?" If yes, `.pivot()` works. If no, use `.pivot_table()` with an `aggfunc`.*

**DataFrame A** is **wide** — each subject is its own column.
```python
# melt() to go long
df_a.melt(id_vars='student', value_vars=['math', 'science', 'english'])
# id_vars='student'  →  the column that stays as the identifier
# value_vars=[...]   →  the columns to collapse into rows
```

**DataFrame B** is **long** — each row is one (city, drink) measurement, no duplicates.
```python
# pivot() to go wide
df_b.pivot(index='city', columns='drink', values='revenue')
# index='city'    →  stays as the row label
# columns='drink' →  unique values become new column names
# values='revenue' →  fills in the cells
```

**DataFrame C** is **long** — but SF/latte and LA/mocha each appear **twice**, so `.pivot()` would error.
```python
# pivot_table() to go wide
df_c.pivot_table(index='city', columns='drink', values='revenue', aggfunc=sum)
# aggfunc=sum  →  adds the two SF/latte values (400 + 220 = 620)
```

</details>

---
### Try It 2: Long → Wide 😊

1. Use `pd.crosstab(index=long_df.date, columns=long_df.category)` to check for duplicates. What do you notice about the counts?

2. Try calling `.pivot()` on `long_df` with `index='date'`, `columns='category'`, `values='sales'`. What error do you get, and why?

3. Fix it by using `.pivot_table()` with `aggfunc=sum`. What does the resulting table represent?

4. Swap `aggfunc=sum` for `aggfunc=len`. What does *this* version tell you? How is it similar to `pd.crosstab()`?

In [ ]:
# 1. Check for duplicate (date, category) combos using pd.crosstab()

In [ ]:
# 2. Try .pivot() — what error do you get?
#    long_df.pivot(index='date', columns='category', values='sales')

In [ ]:
# 3. Fix it with pivot_table() using aggfunc=sum

In [ ]:
# 4. Now try aggfunc=len instead. What does this show?

<details>
<summary>💡 Possible answers — click to peek</summary>
<br>

*`pd.crosstab()` is a quick way to spot duplicates before pivoting — if any cell shows > 1, use `.pivot_table()`.*

```python
# 1. crosstab check
pd.crosstab(index=long_df.date, columns=long_df.category)

# 2. .pivot() raises ValueError — duplicates exist
# long_df.pivot(index='date', columns='category', values='sales')

# 3. pivot_table with sum
long_df.pivot_table(index='date', columns='category', values='sales', aggfunc=sum)

# 4. aggfunc=len shows counts — same as crosstab!
long_df.pivot_table(index='date', columns='category', values='sales', aggfunc=len)
```

</details>

---
## 4. 🔬 Activity — Pets DataFrame

Practice all three cleaning steps on a new dataset.

In [ ]:

# Create a DataFrame with data cleaning and reshaping opportunities
data = {
    'Pet Name': ['Fluffy', 'Whiskers', 'Bubbles', 'Spike', 'Coco', 'Maybelle', 'Snowball'],
    'Date Adopted': ['10-01-2023','03-04-2024','01-10-2024','02-14-2024','11-22-2023','01-04-2024','12-25-2025'],
    'Animal Type': ['Cat', 'Cat', 'Fish', 'Dog', 'Fish', 'Dog', 'Cat'],
    'Pet Age': ['3', '2', '13', '5', '4', '3', '2'],
    'Color': ['White', 'Gray', 'Orange', 'White', 'White', 'Black', 'Black'],
    'Happiness Level': ['High', 'Medium', 'High', 'Low', 'High', 'High', 'Medium']
}
df_pets = pd.DataFrame(data)
df_pets

---
### Try It 1: Clean the Pets DataFrame 😊

1. **Rename columns** to a consistent format (e.g., `snake_case` or `lowercase with spaces` — your choice).

2. **Fix datatypes** — any columns that should be converted? Think about `Pet Age` and `Date Adopted`.

3. **Reshape** — use `.pivot_table()` to find the average age by `Animal Type`. Then try melting the result back to long format.

In [ ]:
# 1. Rename columns

In [ ]:
# 2. Fix datatypes

In [ ]:
# 3. pivot_table: average age by Animal Type

<details>
<summary>💡 Possible answers — click to peek</summary>
<br>

*Many column naming conventions work — consistency is what matters.*

```python
# 1. Rename
df_pets = df_pets.rename(columns={
    'Pet Name': 'pet_name',
    'Date Adopted': 'date_adopted',
    'Animal Type': 'animal_type',
    'Pet Age': 'pet_age',
    'Color': 'color',
    'Happiness Level': 'happiness_level'
})

# 2. Fix types
df_pets['pet_age'] = df_pets['pet_age'].astype(int)
df_pets['date_adopted'] = pd.to_datetime(df_pets['date_adopted'], format='%m-%d-%Y')

# 3. pivot_table
df_pets.pivot_table(index='animal_type', values='pet_age', aggfunc='mean')
```

</details>

---
## Appendix — Cleaning & Reshaping Quick Reference

### Cleaning
```python
df.rename(columns={'old':'new'}, inplace=True)       # rename specific columns
df.columns = ['col1', 'col2', ...]                   # rename all columns
df.drop(columns='col', inplace=True)                 # drop a column
df = df.loc[:, df.nunique() > 1]                     # drop constant columns
df = df.astype({'col': int})                         # convert type
df['col'] = pd.to_datetime(df['col'])                # parse datetime
df.set_index('col', inplace=True)                    # set index
df.sort_values(by='col', ascending=False, inplace=True)  # sort rows
```

### Reshaping
```python
# Wide → Long
df.melt(id_vars='id_col', value_vars=['a','b'])       # melt
df.set_index('id').stack().reset_index(name='value')  # stack

# Long → Wide
df.pivot(index='id', columns='var', values='val')     # pivot (no aggregation)
df.pivot_table(index='id', columns='var',             # pivot_table (aggregates)
               values='val', aggfunc=sum)
```