In [4]:
# Initialize Otter
import otter
grader = otter.Notebook("lab10.ipynb")

# Lab 10: Web Scraping and Manipulating Data

Welcome to Lab 10 of Data Wrangling and Visualization!

## Overview
The web provides a rich source of data, so we often want to work with that information programmatically in order to make sense of it. Sometimes, that data is provided to us by website creators via csv files or through an API (Application Programming Interface). Other times, we need to collect text from the web ourselves.

It is easy to pull HTML from a website but more difficult to find the information we want from HTML.  Parsing the HTML for targeted information and then storing that information in a structured format will be the focus of this activity. Once we have our data in a structured format, we will practice cleaning and reshaping the data.


## In today's lab, we will
- Become familiar with the structure of HTML and CSS by inspecting source code
- Use the Requests and Beautiful Soup libraries to acquire and parse data from websites
- Work through the challenges of web scraping (i.e. turning messy, unstructured data into workable form)
- Use Pandas methods to clean, manipulate, and reshape data for a brief EDA

This activity will make use of the Requests and Beautiful Soup Python modules.
Documentation can be found here: 
- https://docs.python-requests.org/en/latest/
- https://www.crummy.com/software/BeautifulSoup/

### Import packages

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import warnings
warnings.filterwarnings("ignore")
import seaborn as sns
sns.set_style('darkgrid')
import matplotlib.pyplot as plt
import numpy as np

### 1. Scrape and Beautify Cal Poly Humboldt Data

**Question 1.1:** Go to https://pine.humboldt.edu/anstud/cgi-bin/filter.pl?relevant=ft1yr_retention.out. Read through the webpage and inspect its source code. What information does this page provide? Once you have a feel for what is on the webpage, import its contents with the requests module.

In [2]:
# Import the data
page = ...

In [5]:
grader.check("q1_1")

q1_1 results: All test cases passed!

**Question 1.2:** Inspect the text of the data you just imported.

In [6]:
# inspect the text
page_text = ...
page_text

'<HTML>\n<HEAD> <script src="http://www.humboldt.edu/anstud/ga_pine_irp.js" type="text/javascript"></script>  \n<TITLE> First-Time full-time Undergrad Retention 1-year cohorts</TITLE>\n</HEAD>\n<BODY #FFFFFF>\n<p><table border=1 cellpadding=5><TR BGCOLOR=#EEEEEE><th colspan=3>First-Time full-time Undergrads (Freshmen) Retention reports<tr BGCOLOR=#FFFFEE><td>Freshmen cohorts</td><td><a href="filter.pl?relevant=ft1term_retention.out">1-term retention</a>\n&nbsp &nbsp &nbsp<a href="filter.pl?relevant=ft1yr_retention.out">1-year retention</a>\n&nbsp &nbsp &nbsp<a href="filter.pl?relevant=ft2yr_retention.out">2-year retention</a>\n&nbsp &nbsp &nbsp<a href="filter.pl?relevant=ft3yr_retention.out">3-year retention</a>\n&nbsp &nbsp &nbsp</td></tr><tr BGCOLOR=#EEEEEE><td><a href="filter.pl?relevant=trans1yr_retention_UD.out">Transfer Student Retention reports</a>\n&nbsp &nbsp &nbsp</td><td><a href="https://ie.humboldt.edu/grad-reten"> Return to Graduation and Retention data</a></td></tr></table><CENTER><H2>First-Time full-time Undergrad 1-year Retention - Fall Cohorts 2016 - 2025</h2></center><P><TABLE WIDTH=100% BGCOLOR=#FFFFEE ALIGN=CENTER BORDER=1 cellspacing=0 cellpadding=1>\n<TR><TH BGCOLOR=#EEEEEE COLSPAN=11>Overall 1-Year Retention of First-Time full-time Undergrads  \n<BR><SMALL>ft1yr_retention report generated: 03-OCT-25</SMALL></TH></TR>\n<TR BGCOLOR=#EEEEEE><TH><BR></TH><TH>Fall 16<BR></TH><TH>Fall 17<BR></TH><TH>Fall 18<BR></TH><TH>Fall 19<BR></TH><TH>Fall 20<BR></TH><TH>Fall 21<BR></TH><TH>Fall 22<BR></TH><TH>Fall 23<BR></TH><TH>Fall 24<BR></TH><TH>Fall 25<BR></TH></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Initial Cohort</TD><TD>1282</TD><TD>1188</TD><TD>1038</TD><TD>815</TD><TD>532</TD><TD>609</TD><TD>930</TD><TD>937</TD><TD>887</TD><TD>869</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Returned 1-year later</TD><TD>879</TD><TD>846</TD><TD>774</TD><TD>596</TD><TD>392</TD><TD>451</TD><TD>703</TD><TD>712</TD><TD>685</TD><TD>0</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Percent Returning</TD><TD>68.6%</TD><TD>71.2%</TD><TD>74.6%</TD><TD>73.1%</TD><TD>73.7%</TD><TD>74.1%</TD><TD>75.6%</TD><TD>76.0%</TD><TD>77.2%</TD><TD>.0%</TD></TR>\n</TABLE>\n<P><TABLE WIDTH=100% BGCOLOR=#FFFFEE ALIGN=CENTER BORDER=1 cellspacing=0 cellpadding=1>\n<TR><TH BGCOLOR=#EEEEEE COLSPAN=11>First-Time full-time Undergrads by Sex - cohort and pct return 1 year later  \n<BR><SMALL>ft1yr_retention report generated: 03-OCT-25</SMALL></TH></TR>\n<TR BGCOLOR=#EEEEEE><TH>Sex<BR></TH><TH>Fall 16<BR></TH><TH>Fall 17<BR></TH><TH>Fall 18<BR></TH><TH>Fall 19<BR></TH><TH>Fall 20<BR></TH><TH>Fall 21<BR></TH><TH>Fall 22<BR></TH><TH>Fall 23<BR></TH><TH>Fall 24<BR></TH><TH>Fall 25<BR></TH></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>F</TD><TD>728</TD><TD>749</TD><TD>603</TD><TD>476</TD><TD>321</TD><TD>352</TD><TD>513</TD><TD>491</TD><TD>447</TD><TD>385</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>71.8%</TD><TD>74.4%</TD><TD>76.8%</TD><TD>74.2%</TD><TD>75.7%</TD><TD>75.3%</TD><TD>77.6%</TD><TD>77.4%</TD><TD>76.1%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>M</TD><TD>551</TD><TD>433</TD><TD>432</TD><TD>331</TD><TD>204</TD><TD>244</TD><TD>392</TD><TD>426</TD><TD>423</TD><TD>399</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>64.2%</TD><TD>65.8%</TD><TD>71.5%</TD><TD>71.6%</TD><TD>69.6%</TD><TD>70.9%</TD><TD>73.2%</TD><TD>74.9%</TD><TD>78.5%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>N</TD><TD>3</TD><TD>6</TD><TD>3</TD><TD>6</TD><TD>7</TD><TD>13</TD><TD>25</TD><TD>20</TD><TD>17</TD><TD>60</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>66.7%</TD><TD>66.7%</TD><TD>66.7%</TD><TD>83.3%</TD><TD>100.0%</TD><TD>100.0%</TD><TD>72.0%</TD><TD>65.0%</TD><TD>76.5%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>U</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>2</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>25</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>50.0%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>.0%</TD></TR>\n</TABLE>\n<P><TABLE WIDTH=100% BGCOLOR=#FFFFEE ALIGN=CENTER BORDER=1 cellspacing=0 cellpadding=1>\n<TR><TH BGCOLOR=#EEEEEE COLSPAN=11>First-Time full-time Undergrads by URM - cohort and pct return 1 year later  \n<BR><SMALL>ft1yr_retention report generated: 03-OCT-25</SMALL></TH></TR>\n<TR BGCOLOR=#EEEEEE><TH>URM<BR></TH><TH>Fall 16<BR></TH><TH>Fall 17<BR></TH><TH>Fall 18<BR></TH><TH>Fall 19<BR></TH><TH>Fall 20<BR></TH><TH>Fall 21<BR></TH><TH>Fall 22<BR></TH><TH>Fall 23<BR></TH><TH>Fall 24<BR></TH><TH>Fall 25<BR></TH></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Not URM</TD><TD>532</TD><TD>476</TD><TD>453</TD><TD>367</TD><TD>243</TD><TD>360</TD><TD>548</TD><TD>534</TD><TD>508</TD><TD>442</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>71.1%</TD><TD>73.7%</TD><TD>78.6%</TD><TD>72.2%</TD><TD>77.0%</TD><TD>77.8%</TD><TD>79.0%</TD><TD>78.5%</TD><TD>80.5%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>URM</TD><TD>671</TD><TD>645</TD><TD>540</TD><TD>401</TD><TD>274</TD><TD>232</TD><TD>357</TD><TD>370</TD><TD>346</TD><TD>399</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>65.1%</TD><TD>69.3%</TD><TD>71.7%</TD><TD>74.3%</TD><TD>71.9%</TD><TD>68.5%</TD><TD>71.7%</TD><TD>72.4%</TD><TD>72.5%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Unknown</TD><TD>79</TD><TD>67</TD><TD>45</TD><TD>47</TD><TD>15</TD><TD>17</TD><TD>25</TD><TD>33</TD><TD>33</TD><TD>28</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>81.0%</TD><TD>71.6%</TD><TD>68.9%</TD><TD>70.2%</TD><TD>53.3%</TD><TD>70.6%</TD><TD>56.0%</TD><TD>75.8%</TD><TD>75.8%</TD><TD>.0%</TD></TR>\n</TABLE>\n<P><TABLE WIDTH=100% BGCOLOR=#FFFFEE ALIGN=CENTER BORDER=1 cellspacing=0 cellpadding=1>\n<TR><TH BGCOLOR=#EEEEEE COLSPAN=11>First-Time full-time Undergrads CSU/IPEDS Ethnicity - cohort and pct return 1 year later  \n<BR><SMALL>ft1yr_retention report generated: 03-OCT-25</SMALL></TH></TR>\n<TR BGCOLOR=#EEEEEE><TH>CSU/IPEDS Ethnicity<BR></TH><TH>Fall 16<BR></TH><TH>Fall 17<BR></TH><TH>Fall 18<BR></TH><TH>Fall 19<BR></TH><TH>Fall 20<BR></TH><TH>Fall 21<BR></TH><TH>Fall 22<BR></TH><TH>Fall 23<BR></TH><TH>Fall 24<BR></TH><TH>Fall 25<BR></TH></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>African American</TD><TD>51</TD><TD>57</TD><TD>48</TD><TD>29</TD><TD>23</TD><TD>14</TD><TD>32</TD><TD>20</TD><TD>18</TD><TD>36</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>64.7%</TD><TD>86.0%</TD><TD>60.4%</TD><TD>72.4%</TD><TD>69.6%</TD><TD>71.4%</TD><TD>71.9%</TD><TD>65.0%</TD><TD>61.1%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>American Indian</TD><TD>11</TD><TD>12</TD><TD>11</TD><TD>7</TD><TD>9</TD><TD>6</TD><TD>8</TD><TD>7</TD><TD>9</TD><TD>13</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>72.7%</TD><TD>66.7%</TD><TD>81.8%</TD><TD>85.7%</TD><TD>88.9%</TD><TD>66.7%</TD><TD>50.0%</TD><TD>100.0%</TD><TD>55.6%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Asian American</TD><TD>31</TD><TD>21</TD><TD>22</TD><TD>12</TD><TD>17</TD><TD>15</TD><TD>30</TD><TD>32</TD><TD>23</TD><TD>25</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>74.2%</TD><TD>71.4%</TD><TD>72.7%</TD><TD>83.3%</TD><TD>70.6%</TD><TD>60.0%</TD><TD>80.0%</TD><TD>93.8%</TD><TD>87.0%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Hispanic/Latino</TD><TD>545</TD><TD>517</TD><TD>444</TD><TD>328</TD><TD>214</TD><TD>190</TD><TD>272</TD><TD>302</TD><TD>275</TD><TD>304</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>64.8%</TD><TD>67.9%</TD><TD>73.0%</TD><TD>74.4%</TD><TD>71.5%</TD><TD>68.4%</TD><TD>70.6%</TD><TD>72.5%</TD><TD>73.8%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Nonresident Alien</TD><TD>18</TD><TD>16</TD><TD>10</TD><TD>6</TD><TD>5</TD><TD>4</TD><TD>5</TD><TD>4</TD><TD>6</TD><TD>4</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>83.3%</TD><TD>68.8%</TD><TD>60.0%</TD><TD>66.7%</TD><TD>60.0%</TD><TD>75.0%</TD><TD>60.0%</TD><TD>75.0%</TD><TD>83.3%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Pacific Islander</TD><TD>4</TD><TD>4</TD><TD>5</TD><TD>1</TD><TD>1</TD><TD>1</TD><TD>2</TD><TD>4</TD><TD>3</TD><TD>3</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>50.0%</TD><TD>50.0%</TD><TD>60.0%</TD><TD>100.0%</TD><TD>100.0%</TD><TD>100.0%</TD><TD>50.0%</TD><TD>75.0%</TD><TD>66.7%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Two or More Races</TD><TD>100</TD><TD>85</TD><TD>53</TD><TD>55</TD><TD>36</TD><TD>40</TD><TD>70</TD><TD>77</TD><TD>74</TD><TD>72</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>68.0%</TD><TD>69.4%</TD><TD>69.8%</TD><TD>69.1%</TD><TD>72.2%</TD><TD>72.5%</TD><TD>82.9%</TD><TD>77.9%</TD><TD>74.3%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Unknown</TD><TD>61</TD><TD>51</TD><TD>35</TD><TD>41</TD><TD>10</TD><TD>13</TD><TD>20</TD><TD>29</TD><TD>27</TD><TD>24</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>80.3%</TD><TD>72.5%</TD><TD>71.4%</TD><TD>70.7%</TD><TD>50.0%</TD><TD>69.2%</TD><TD>55.0%</TD><TD>75.9%</TD><TD>74.1%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>White</TD><TD>461</TD><TD>425</TD><TD>410</TD><TD>336</TD><TD>217</TD><TD>326</TD><TD>491</TD><TD>462</TD><TD>452</TD><TD>388</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>71.1%</TD><TD>73.9%</TD><TD>79.3%</TD><TD>72.3%</TD><TD>77.4%</TD><TD>78.5%</TD><TD>78.8%</TD><TD>76.8%</TD><TD>80.5%</TD><TD>.0%</TD></TR>\n</TABLE>\n<P><TABLE WIDTH=100% BGCOLOR=#FFFFEE ALIGN=CENTER BORDER=1 cellspacing=0 cellpadding=1>\n<TR><TH BGCOLOR=#EEEEEE COLSPAN=12>First-Time full-time Undergrads Sex by URM - cohort and pct return 1 year later  \n<BR><SMALL>ft1yr_retention report generated: 03-OCT-25</SMALL></TH></TR>\n<TR BGCOLOR=#EEEEEE><TH>Sex<BR></TH><TH>URM<BR></TH><TH>Fall 16<BR></TH><TH>Fall 17<BR></TH><TH>Fall 18<BR></TH><TH>Fall 19<BR></TH><TH>Fall 20<BR></TH><TH>Fall 21<BR></TH><TH>Fall 22<BR></TH><TH>Fall 23<BR></TH><TH>Fall 24<BR></TH><TH>Fall 25<BR></TH></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>F</TD><TD ALIGN=LEFT>Not URM</TD><TD>277</TD><TD>295</TD><TD>252</TD><TD>200</TD><TD>146</TD><TD>205</TD><TD>296</TD><TD>271</TD><TD>238</TD><TD>195</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT><BR></TD><TD>75.1%</TD><TD>78.3%</TD><TD>79.4%</TD><TD>69.5%</TD><TD>79.5%</TD><TD>78.5%</TD><TD>81.1%</TD><TD>79.3%</TD><TD>76.9%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT>URM</TD><TD>401</TD><TD>410</TD><TD>327</TD><TD>252</TD><TD>166</TD><TD>145</TD><TD>205</TD><TD>204</TD><TD>194</TD><TD>177</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT><BR></TD><TD>68.3%</TD><TD>71.2%</TD><TD>75.5%</TD><TD>77.8%</TD><TD>72.9%</TD><TD>70.3%</TD><TD>73.2%</TD><TD>74.5%</TD><TD>74.7%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT>Unknown</TD><TD>50</TD><TD>44</TD><TD>24</TD><TD>24</TD><TD>9</TD><TD>2</TD><TD>12</TD><TD>16</TD><TD>15</TD><TD>13</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT><BR></TD><TD>82.0%</TD><TD>77.3%</TD><TD>66.7%</TD><TD>75.0%</TD><TD>66.7%</TD><TD>100.0%</TD><TD>66.7%</TD><TD>81.3%</TD><TD>80.0%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>M</TD><TD ALIGN=LEFT>Not URM</TD><TD>254</TD><TD>177</TD><TD>199</TD><TD>162</TD><TD>93</TD><TD>145</TD><TD>238</TD><TD>252</TD><TD>260</TD><TD>194</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT><BR></TD><TD>66.5%</TD><TD>66.7%</TD><TD>77.9%</TD><TD>74.7%</TD><TD>72.0%</TD><TD>75.2%</TD><TD>76.5%</TD><TD>77.8%</TD><TD>83.8%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT>URM</TD><TD>268</TD><TD>234</TD><TD>212</TD><TD>147</TD><TD>105</TD><TD>84</TD><TD>142</TD><TD>159</TD><TD>145</TD><TD>198</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT><BR></TD><TD>60.4%</TD><TD>65.8%</TD><TD>65.6%</TD><TD>68.7%</TD><TD>69.5%</TD><TD>64.3%</TD><TD>69.7%</TD><TD>71.1%</TD><TD>69.7%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT>Unknown</TD><TD>29</TD><TD>22</TD><TD>21</TD><TD>22</TD><TD>6</TD><TD>15</TD><TD>12</TD><TD>15</TD><TD>18</TD><TD>7</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT><BR></TD><TD>79.3%</TD><TD>59.1%</TD><TD>71.4%</TD><TD>68.2%</TD><TD>33.3%</TD><TD>66.7%</TD><TD>50.0%</TD><TD>66.7%</TD><TD>72.2%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>N</TD><TD ALIGN=LEFT>Not URM</TD><TD>1</TD><TD>4</TD><TD>2</TD><TD>4</TD><TD>4</TD><TD>10</TD><TD>14</TD><TD>11</TD><TD>10</TD><TD>41</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT><BR></TD><TD>100.0%</TD><TD>50.0%</TD><TD>50.0%</TD><TD>100.0%</TD><TD>100.0%</TD><TD>100.0%</TD><TD>78.6%</TD><TD>72.7%</TD><TD>80.0%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT>URM</TD><TD>2</TD><TD>1</TD><TD>1</TD><TD>2</TD><TD>3</TD><TD>3</TD><TD>10</TD><TD>7</TD><TD>7</TD><TD>17</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT><BR></TD><TD>50.0%</TD><TD>100.0%</TD><TD>100.0%</TD><TD>50.0%</TD><TD>100.0%</TD><TD>100.0%</TD><TD>70.0%</TD><TD>42.9%</TD><TD>71.4%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT>Unknown</TD><TD>0</TD><TD>1</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>1</TD><TD>2</TD><TD>0</TD><TD>2</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT><BR></TD><TD>%</TD><TD>100.0%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>.0%</TD><TD>100.0%</TD><TD>%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>U</TD><TD ALIGN=LEFT>Not URM</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>1</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>12</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT><BR></TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>100.0%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT>URM</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>7</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT><BR></TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT>Unknown</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>1</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>0</TD><TD>6</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD ALIGN=LEFT><BR></TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>.0%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>%</TD><TD>.0%</TD></TR>\n</TABLE>\n<P><TABLE WIDTH=100% BGCOLOR=#FFFFEE ALIGN=CENTER BORDER=1 cellspacing=0 cellpadding=1>\n<TR><TH BGCOLOR=#EEEEEE COLSPAN=11>First-Time full-time Undergrads by Exceptional Admit Status - cohort and pct return 1 year later  \n<BR><SMALL>ft1yr_retention report generated: 03-OCT-25</SMALL></TH></TR>\n<TR BGCOLOR=#EEEEEE><TH>Exception<BR></TH><TH>Fall 16<BR></TH><TH>Fall 17<BR></TH><TH>Fall 18<BR></TH><TH>Fall 19<BR></TH><TH>Fall 20<BR></TH><TH>Fall 21<BR></TH><TH>Fall 22<BR></TH><TH>Fall 23<BR></TH><TH>Fall 24<BR></TH><TH>Fall 25<BR></TH></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>N</TD><TD>1220</TD><TD>1140</TD><TD>989</TD><TD>765</TD><TD>515</TD><TD>572</TD><TD>868</TD><TD>899</TD><TD>875</TD><TD>849</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>69.1%</TD><TD>71.7%</TD><TD>76.3%</TD><TD>73.5%</TD><TD>73.6%</TD><TD>75.5%</TD><TD>75.3%</TD><TD>76.4%</TD><TD>77.1%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Y</TD><TD>62</TD><TD>48</TD><TD>49</TD><TD>50</TD><TD>17</TD><TD>37</TD><TD>62</TD><TD>38</TD><TD>12</TD><TD>20</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>58.1%</TD><TD>60.4%</TD><TD>38.8%</TD><TD>68.0%</TD><TD>76.5%</TD><TD>51.4%</TD><TD>79.0%</TD><TD>65.8%</TD><TD>83.3%</TD><TD>.0%</TD></TR>\n</TABLE>\n<P><TABLE WIDTH=100% BGCOLOR=#FFFFEE ALIGN=CENTER BORDER=1 cellspacing=0 cellpadding=1>\n<TR><TH BGCOLOR=#EEEEEE COLSPAN=11>First-Time full-time Undergrads by EOP participation - cohort and pct return 1 year later  \n<BR><SMALL>ft1yr_retention report generated: 03-OCT-25</SMALL></TH></TR>\n<TR BGCOLOR=#EEEEEE><TH>EOP<BR></TH><TH>Fall 16<BR></TH><TH>Fall 17<BR></TH><TH>Fall 18<BR></TH><TH>Fall 19<BR></TH><TH>Fall 20<BR></TH><TH>Fall 21<BR></TH><TH>Fall 22<BR></TH><TH>Fall 23<BR></TH><TH>Fall 24<BR></TH><TH>Fall 25<BR></TH></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>N</TD><TD>1148</TD><TD>1040</TD><TD>858</TD><TD>710</TD><TD>446</TD><TD>534</TD><TD>822</TD><TD>844</TD><TD>816</TD><TD>787</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>68.0%</TD><TD>70.5%</TD><TD>75.4%</TD><TD>72.3%</TD><TD>73.8%</TD><TD>74.9%</TD><TD>76.0%</TD><TD>76.3%</TD><TD>77.2%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Y</TD><TD>134</TD><TD>148</TD><TD>180</TD><TD>105</TD><TD>86</TD><TD>75</TD><TD>108</TD><TD>93</TD><TD>71</TD><TD>82</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>73.1%</TD><TD>76.4%</TD><TD>70.6%</TD><TD>79.0%</TD><TD>73.3%</TD><TD>68.0%</TD><TD>72.2%</TD><TD>73.1%</TD><TD>77.5%</TD><TD>.0%</TD></TR>\n</TABLE>\n<P><TABLE WIDTH=100% BGCOLOR=#FFFFEE ALIGN=CENTER BORDER=1 cellspacing=0 cellpadding=1>\n<TR><TH BGCOLOR=#EEEEEE COLSPAN=11>First-Time full-time Undergrads by Academic Standing at END of first TERM - cohort and pct return 1 year later  \n<BR><SMALL>ft1yr_retention report generated: 03-OCT-25</SMALL></TH></TR>\n<TR BGCOLOR=#EEEEEE><TH>Acad Standing<BR></TH><TH>Fall 16<BR></TH><TH>Fall 17<BR></TH><TH>Fall 18<BR></TH><TH>Fall 19<BR></TH><TH>Fall 20<BR></TH><TH>Fall 21<BR></TH><TH>Fall 22<BR></TH><TH>Fall 23<BR></TH><TH>Fall 24<BR></TH><TH>Fall 25<BR></TH></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Good Standing</TD><TD>940</TD><TD>932</TD><TD>784</TD><TD>613</TD><TD>440</TD><TD>461</TD><TD>703</TD><TD>740</TD><TD>672</TD><TD>869</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>78.0%</TD><TD>79.7%</TD><TD>82.4%</TD><TD>80.1%</TD><TD>83.4%</TD><TD>81.8%</TD><TD>85.5%</TD><TD>84.1%</TD><TD>83.9%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Prob/Disq/Rein</TD><TD>342</TD><TD>256</TD><TD>254</TD><TD>202</TD><TD>92</TD><TD>148</TD><TD>227</TD><TD>197</TD><TD>215</TD><TD>0</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>42.7%</TD><TD>40.2%</TD><TD>50.4%</TD><TD>52.0%</TD><TD>27.2%</TD><TD>50.0%</TD><TD>44.9%</TD><TD>45.7%</TD><TD>56.3%</TD><TD>%</TD></TR>\n</TABLE>\n<P><TABLE WIDTH=100% BGCOLOR=#FFFFEE ALIGN=CENTER BORDER=1 cellspacing=0 cellpadding=1>\n<TR><TH BGCOLOR=#EEEEEE COLSPAN=11>First-Time full-time Undergrads by Academic Standing at END of first YEAR - cohort and pct return 1 year later  \n<BR><SMALL>ft1yr_retention report generated: 03-OCT-25</SMALL></TH></TR>\n<TR BGCOLOR=#EEEEEE><TH>Acad Standing<BR></TH><TH>Fall 16<BR></TH><TH>Fall 17<BR></TH><TH>Fall 18<BR></TH><TH>Fall 19<BR></TH><TH>Fall 20<BR></TH><TH>Fall 21<BR></TH><TH>Fall 22<BR></TH><TH>Fall 23<BR></TH><TH>Fall 24<BR></TH><TH>Fall 25<BR></TH></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Good Standing</TD><TD>984</TD><TD>921</TD><TD>825</TD><TD>666</TD><TD>429</TD><TD>463</TD><TD>707</TD><TD>753</TD><TD>680</TD><TD>869</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>79.9%</TD><TD>80.2%</TD><TD>83.4%</TD><TD>79.7%</TD><TD>84.1%</TD><TD>84.2%</TD><TD>87.0%</TD><TD>85.5%</TD><TD>86.0%</TD><TD>.0%</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT>Prob/Disq/Rein</TD><TD>298</TD><TD>267</TD><TD>213</TD><TD>149</TD><TD>103</TD><TD>146</TD><TD>223</TD><TD>184</TD><TD>207</TD><TD>0</TD></TR>\n<TR ALIGN=RIGHT><TD ALIGN=LEFT><BR></TD><TD>31.2%</TD><TD>40.1%</TD><TD>40.4%</TD><TD>43.6%</TD><TD>30.1%</TD><TD>41.8%</TD><TD>39.5%</TD><TD>37.0%</TD><TD>48.3%</TD><TD>%</TD></TR>\n</TABLE>\n<P><TABLE WIDTH=100% BGCOLOR=#FFFFEE ALIGN=CENTER BORDER=1 cellspacing=0 cellpadding=1>\n<TR><TH BGCOLOR=#EEEEEE COLSPAN=11>First-Time full-time Undergrads by First Generation status - cohort and pct return 1 year later  \n<BR><SMALL>ft1yr_retention report generated: 03-OCT-25</SMALL></TH></TR>\n<TR BGCOLOR=#EEEEEE><TH>First-Generation<BR></TH><TH>Fall 16<BR></TH><TH>Fall 17<BR></TH><TH>Fall 18<BR></TH><TH>Fall 19<BR></TH><TH>Fall 20<BR></TH><TH>Fall 21<BR></TH><TH>Fall 22<BR><

In [7]:
grader.check("q1_2")

q1_2 results: All test cases passed!

**Question 1.3:** Create a Beautiful Soup object from `page_text`.

In [9]:
# Create soup object
soup = ...
soup

<html>
<head> <script src="http://www.humboldt.edu/anstud/ga_pine_irp.js" type="text/javascript"></script>
<title> First-Time full-time Undergrad Retention 1-year cohorts</title>
</head>
<body #ffffff="">
<p></p><table border="1" cellpadding="5"><tr bgcolor="#EEEEEE"><th colspan="3">First-Time full-time Undergrads (Freshmen) Retention reports</th></tr><tr bgcolor="#FFFFEE"><td>Freshmen cohorts</td><td><a href="filter.pl?relevant=ft1term_retention.out">1-term retention</a>
     <a href="filter.pl?relevant=ft1yr_retention.out">1-year retention</a>
     <a href="filter.pl?relevant=ft2yr_retention.out">2-year retention</a>
     <a href="filter.pl?relevant=ft3yr_retention.out">3-year retention</a>
     </td></tr><tr bgcolor="#EEEEEE"><td><a href="filter.pl?relevant=trans1yr_retention_UD.out">Transfer Student Retention reports</a>
     </td><td><a href="https://ie.humboldt.edu/grad-reten"> Return to Graduation and Retention data</a></td></tr></table><center><h2>First-Time full-time Undergrad 1-year Retention - Fall Cohorts 2016 - 2025</h2></center><p></p><table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">
<tr><th bgcolor="#EEEEEE" colspan="11">Overall 1-Year Retention of First-Time full-time Undergrads
<br/><small>ft1yr_retention report generated: 03-OCT-25</small></th></tr>
<tr bgcolor="#EEEEEE"><th><br/></th><th>Fall 16<br/></th><th>Fall 17<br/></th><th>Fall 18<br/></th><th>Fall 19<br/></th><th>Fall 20<br/></th><th>Fall 21<br/></th><th>Fall 22<br/></th><th>Fall 23<br/></th><th>Fall 24<br/></th><th>Fall 25<br/></th></tr>
<tr align="RIGHT"><td align="LEFT">Initial Cohort</td><td>1282</td><td>1188</td><td>1038</td><td>815</td><td>532</td><td>609</td><td>930</td><td>937</td><td>887</td><td>869</td></tr>
<tr align="RIGHT"><td align="LEFT">Returned 1-year later</td><td>879</td><td>846</td><td>774</td><td>596</td><td>392</td><td>451</td><td>703</td><td>712</td><td>685</td><td>0</td></tr>
<tr align="RIGHT"><td align="LEFT">Percent Returning</td><td>68.6%</td><td>71.2%</td><td>74.6%</td><td>73.1%</td><td>73.7%</td><td>74.1%</td><td>75.6%</td><td>76.0%</td><td>77.2%</td><td>.0%</td></tr>
</table>
<p></p><table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">
<tr><th bgcolor="#EEEEEE" colspan="11">First-Time full-time Undergrads by Sex - cohort and pct return 1 year later
<br/><small>ft1yr_retention report generated: 03-OCT-25</small></th></tr>
<tr bgcolor="#EEEEEE"><th>Sex<br/></th><th>Fall 16<br/></th><th>Fall 17<br/></th><th>Fall 18<br/></th><th>Fall 19<br/></th><th>Fall 20<br/></th><th>Fall 21<br/></th><th>Fall 22<br/></th><th>Fall 23<br/></th><th>Fall 24<br/></th><th>Fall 25<br/></th></tr>
<tr align="RIGHT"><td align="LEFT">F</td><td>728</td><td>749</td><td>603</td><td>476</td><td>321</td><td>352</td><td>513</td><td>491</td><td>447</td><td>385</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>71.8%</td><td>74.4%</td><td>76.8%</td><td>74.2%</td><td>75.7%</td><td>75.3%</td><td>77.6%</td><td>77.4%</td><td>76.1%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">M</td><td>551</td><td>433</td><td>432</td><td>331</td><td>204</td><td>244</td><td>392</td><td>426</td><td>423</td><td>399</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>64.2%</td><td>65.8%</td><td>71.5%</td><td>71.6%</td><td>69.6%</td><td>70.9%</td><td>73.2%</td><td>74.9%</td><td>78.5%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">N</td><td>3</td><td>6</td><td>3</td><td>6</td><td>7</td><td>13</td><td>25</td><td>20</td><td>17</td><td>60</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>66.7%</td><td>66.7%</td><td>66.7%</td><td>83.3%</td><td>100.0%</td><td>100.0%</td><td>72.0%</td><td>65.0%</td><td>76.5%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">U</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>25</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>50.0%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>.0%</td></tr>
</table>
<p></p><table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">
<tr><th bgcolor="#EEEEEE" colspan="11">First-Time full-time Undergrads by URM - cohort and pct return 1 year later
<br/><small>ft1yr_retention report generated: 03-OCT-25</small></th></tr>
<tr bgcolor="#EEEEEE"><th>URM<br/></th><th>Fall 16<br/></th><th>Fall 17<br/></th><th>Fall 18<br/></th><th>Fall 19<br/></th><th>Fall 20<br/></th><th>Fall 21<br/></th><th>Fall 22<br/></th><th>Fall 23<br/></th><th>Fall 24<br/></th><th>Fall 25<br/></th></tr>
<tr align="RIGHT"><td align="LEFT">Not URM</td><td>532</td><td>476</td><td>453</td><td>367</td><td>243</td><td>360</td><td>548</td><td>534</td><td>508</td><td>442</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>71.1%</td><td>73.7%</td><td>78.6%</td><td>72.2%</td><td>77.0%</td><td>77.8%</td><td>79.0%</td><td>78.5%</td><td>80.5%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">URM</td><td>671</td><td>645</td><td>540</td><td>401</td><td>274</td><td>232</td><td>357</td><td>370</td><td>346</td><td>399</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>65.1%</td><td>69.3%</td><td>71.7%</td><td>74.3%</td><td>71.9%</td><td>68.5%</td><td>71.7%</td><td>72.4%</td><td>72.5%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Unknown</td><td>79</td><td>67</td><td>45</td><td>47</td><td>15</td><td>17</td><td>25</td><td>33</td><td>33</td><td>28</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>81.0%</td><td>71.6%</td><td>68.9%</td><td>70.2%</td><td>53.3%</td><td>70.6%</td><td>56.0%</td><td>75.8%</td><td>75.8%</td><td>.0%</td></tr>
</table>
<p></p><table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">
<tr><th bgcolor="#EEEEEE" colspan="11">First-Time full-time Undergrads CSU/IPEDS Ethnicity - cohort and pct return 1 year later
<br/><small>ft1yr_retention report generated: 03-OCT-25</small></th></tr>
<tr bgcolor="#EEEEEE"><th>CSU/IPEDS Ethnicity<br/></th><th>Fall 16<br/></th><th>Fall 17<br/></th><th>Fall 18<br/></th><th>Fall 19<br/></th><th>Fall 20<br/></th><th>Fall 21<br/></th><th>Fall 22<br/></th><th>Fall 23<br/></th><th>Fall 24<br/></th><th>Fall 25<br/></th></tr>
<tr align="RIGHT"><td align="LEFT">African American</td><td>51</td><td>57</td><td>48</td><td>29</td><td>23</td><td>14</td><td>32</td><td>20</td><td>18</td><td>36</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>64.7%</td><td>86.0%</td><td>60.4%</td><td>72.4%</td><td>69.6%</td><td>71.4%</td><td>71.9%</td><td>65.0%</td><td>61.1%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">American Indian</td><td>11</td><td>12</td><td>11</td><td>7</td><td>9</td><td>6</td><td>8</td><td>7</td><td>9</td><td>13</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>72.7%</td><td>66.7%</td><td>81.8%</td><td>85.7%</td><td>88.9%</td><td>66.7%</td><td>50.0%</td><td>100.0%</td><td>55.6%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Asian American</td><td>31</td><td>21</td><td>22</td><td>12</td><td>17</td><td>15</td><td>30</td><td>32</td><td>23</td><td>25</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>74.2%</td><td>71.4%</td><td>72.7%</td><td>83.3%</td><td>70.6%</td><td>60.0%</td><td>80.0%</td><td>93.8%</td><td>87.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Hispanic/Latino</td><td>545</td><td>517</td><td>444</td><td>328</td><td>214</td><td>190</td><td>272</td><td>302</td><td>275</td><td>304</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>64.8%</td><td>67.9%</td><td>73.0%</td><td>74.4%</td><td>71.5%</td><td>68.4%</td><td>70.6%</td><td>72.5%</td><td>73.8%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Nonresident Alien</td><td>18</td><td>16</td><td>10</td><td>6</td><td>5</td><td>4</td><td>5</td><td>4</td><td>6</td><td>4</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>83.3%</td><td>68.8%</td><td>60.0%</td><td>66.7%</td><td>60.0%</td><td>75.0%</td><td>60.0%</td><td>75.0%</td><td>83.3%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Pacific Islander</td><td>4</td><td>4</td><td>5</td><td>1</td><td>1</td><td>1</td><td>2</td><td>4</td><td>3</td><td>3</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>50.0%</td><td>50.0%</td><td>60.0%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>50.0%</td><td>75.0%</td><td>66.7%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Two or More Races</td><td>100</td><td>85</td><td>53</td><td>55</td><td>36</td><td>40</td><td>70</td><td>77</td><td>74</td><td>72</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>68.0%</td><td>69.4%</td><td>69.8%</td><td>69.1%</td><td>72.2%</td><td>72.5%</td><td>82.9%</td><td>77.9%</td><td>74.3%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Unknown</td><td>61</td><td>51</td><td>35</td><td>41</td><td>10</td><td>13</td><td>20</td><td>29</td><td>27</td><td>24</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>80.3%</td><td>72.5%</td><td>71.4%</td><td>70.7%</td><td>50.0%</td><td>69.2%</td><td>55.0%</td><td>75.9%</td><td>74.1%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">White</td><td>461</td><td>425</td><td>410</td><td>336</td><td>217</td><td>326</td><td>491</td><td>462</td><td>452</td><td>388</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>71.1%</td><td>73.9%</td><td>79.3%</td><td>72.3%</td><td>77.4%</td><td>78.5%</td><td>78.8%</td><td>76.8%</td><td>80.5%</td><td>.0%</td></tr>
</table>
<p></p><table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">
<tr><th bgcolor="#EEEEEE" colspan="12">First-Time full-time Undergrads Sex by URM - cohort and pct return 1 year later
<br/><small>ft1yr_retention report generated: 03-OCT-25</small></th></tr>
<tr bgcolor="#EEEEEE"><th>Sex<br/></th><th>URM<br/></th><th>Fall 16<br/></th><th>Fall 17<br/></th><th>Fall 18<br/></th><th>Fall 19<br/></th><th>Fall 20<br/></th><th>Fall 21<br/></th><th>Fall 22<br/></th><th>Fall 23<br/></th><th>Fall 24<br/></th><th>Fall 25<br/></th></tr>
<tr align="RIGHT"><td align="LEFT">F</td><td align="LEFT">Not URM</td><td>277</td><td>295</td><td>252</td><td>200</td><td>146</td><td>205</td><td>296</td><td>271</td><td>238</td><td>195</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT"><br/></td><td>75.1%</td><td>78.3%</td><td>79.4%</td><td>69.5%</td><td>79.5%</td><td>78.5%</td><td>81.1%</td><td>79.3%</td><td>76.9%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT">URM</td><td>401</td><td>410</td><td>327</td><td>252</td><td>166</td><td>145</td><td>205</td><td>204</td><td>194</td><td>177</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT"><br/></td><td>68.3%</td><td>71.2%</td><td>75.5%</td><td>77.8%</td><td>72.9%</td><td>70.3%</td><td>73.2%</td><td>74.5%</td><td>74.7%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT">Unknown</td><td>50</td><td>44</td><td>24</td><td>24</td><td>9</td><td>2</td><td>12</td><td>16</td><td>15</td><td>13</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT"><br/></td><td>82.0%</td><td>77.3%</td><td>66.7%</td><td>75.0%</td><td>66.7%</td><td>100.0%</td><td>66.7%</td><td>81.3%</td><td>80.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">M</td><td align="LEFT">Not URM</td><td>254</td><td>177</td><td>199</td><td>162</td><td>93</td><td>145</td><td>238</td><td>252</td><td>260</td><td>194</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT"><br/></td><td>66.5%</td><td>66.7%</td><td>77.9%</td><td>74.7%</td><td>72.0%</td><td>75.2%</td><td>76.5%</td><td>77.8%</td><td>83.8%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT">URM</td><td>268</td><td>234</td><td>212</td><td>147</td><td>105</td><td>84</td><td>142</td><td>159</td><td>145</td><td>198</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT"><br/></td><td>60.4%</td><td>65.8%</td><td>65.6%</td><td>68.7%</td><td>69.5%</td><td>64.3%</td><td>69.7%</td><td>71.1%</td><td>69.7%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT">Unknown</td><td>29</td><td>22</td><td>21</td><td>22</td><td>6</td><td>15</td><td>12</td><td>15</td><td>18</td><td>7</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT"><br/></td><td>79.3%</td><td>59.1%</td><td>71.4%</td><td>68.2%</td><td>33.3%</td><td>66.7%</td><td>50.0%</td><td>66.7%</td><td>72.2%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">N</td><td align="LEFT">Not URM</td><td>1</td><td>4</td><td>2</td><td>4</td><td>4</td><td>10</td><td>14</td><td>11</td><td>10</td><td>41</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT"><br/></td><td>100.0%</td><td>50.0%</td><td>50.0%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>78.6%</td><td>72.7%</td><td>80.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT">URM</td><td>2</td><td>1</td><td>1</td><td>2</td><td>3</td><td>3</td><td>10</td><td>7</td><td>7</td><td>17</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT"><br/></td><td>50.0%</td><td>100.0%</td><td>100.0%</td><td>50.0%</td><td>100.0%</td><td>100.0%</td><td>70.0%</td><td>42.9%</td><td>71.4%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT">Unknown</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>2</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT"><br/></td><td>%</td><td>100.0%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>.0%</td><td>100.0%</td><td>%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">U</td><td align="LEFT">Not URM</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>100.0%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT">URM</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT">Unknown</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>.0%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>.0%</td></tr>
</table>
<p></p><table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">
<tr><th bgcolor="#EEEEEE" colspan="11">First-Time full-time Undergrads by Exceptional Admit Status - cohort and pct return 1 year later
<br/><small>ft1yr_retention report generated: 03-OCT-25</small></th></tr>
<tr bgcolor="#EEEEEE"><th>Exception<br/></th><th>Fall 16<br/></th><th>Fall 17<br/></th><th>Fall 18<br/></th><th>Fall 19<br/></th><th>Fall 20<br/></th><th>Fall 21<br/></th><th>Fall 22<br/></th><th>Fall 23<br/></th><th>Fall 24<br/></th><th>Fall 25<br/></th></tr>
<tr align="RIGHT"><td align="LEFT">N</td><td>1220</td><td>1140</td><td>989</td><td>765</td><td>515</td><td>572</td><td>868</td><td>899</td><td>875</td><td>849</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>69.1%</td><td>71.7%</td><td>76.3%</td><td>73.5%</td><td>73.6%</td><td>75.5%</td><td>75.3%</td><td>76.4%</td><td>77.1%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Y</td><td>62</td><td>48</td><td>49</td><td>50</td><td>17</td><td>37</td><td>62</td><td>38</td><td>12</td><td>20</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>58.1%</td><td>60.4%</td><td>38.8%</td><td>68.0%</td><td>76.5%</td><td>51.4%</td><td>79.0%</td><td>65.8%</td><td>83.3%</td><td>.0%</td></tr>
</table>
<p></p><table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">
<tr><th bgcolor="#EEEEEE" colspan="11">First-Time full-time Undergrads by EOP participation - cohort and pct return 1 year later
<br/><small>ft1yr_retention report generated: 03-OCT-25</small></th></tr>
<tr bgcolor="#EEEEEE"><th>EOP<br/></th><th>Fall 16<br/></th><th>Fall 17<br/></th><th>Fall 18<br/></th><th>Fall 19<br/></th><th>Fall 20<br/></th><th>Fall 21<br/></th><th>Fall 22<br/></th><th>Fall 23<br/></th><th>Fall 24<br/></th><th>Fall 25<br/></th></tr>
<tr align="RIGHT"><td align="LEFT">N</td><td>1148</td><td>1040</td><td>858</td><td>710</td><td>446</td><td>534</td><td>822</td><td>844</td><td>816</td><td>787</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>68.0%</td><td>70.5%</td><td>75.4%</td><td>72.3%</td><td>73.8%</td><td>74.9%</td><td>76.0%</td><td>76.3%</td><td>77.2%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Y</td><td>134</td><td>148</td><td>180</td><td>105</td><td>86</td><td>75</td><td>108</td><td>93</td><td>71</td><td>82</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>73.1%</td><td>76.4%</td><td>70.6%</td><td>79.0%</td><td>73.3%</td><td>68.0%</td><td>72.2%</td><td>73.1%</td><td>77.5%</td><td>.0%</td></tr>
</table>
<p></p><table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">
<tr><th bgcolor="#EEEEEE" colspan="11">First-Time full-time Undergrads by Academic Standing at END of first TERM - cohort and pct return 1 year later
<br/><small>ft1yr_retention report generated: 03-OCT-25</small></th></tr>
<tr bgcolor="#EEEEEE"><th>Acad Standing<br/></th><th>Fall 16<br/></th><th>Fall 17<br/></th><th>Fall 18<br/></th><th>Fall 19<br/></th><th>Fall 20<br/></th><th>Fall 21<br/></th><th>Fall 22<br/></th><th>Fall 23<br/></th><th>Fall 24<br/></th><th>Fall 25<br/></th></tr>
<tr align="RIGHT"><td align="LEFT">Good Standing</td><td>940</td><td>932</td><td>784</td><td>613</td><td>440</td><td>461</td><td>703</td><td>740</td><td>672</td><td>869</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>78.0%</td><td>79.7%</td><td>82.4%</td><td>80.1%</td><td>83.4%</td><td>81.8%</td><td>85.5%</td><td>84.1%</td><td>83.9%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Prob/Disq/Rein</td><td>342</td><td>256</td><td>254</td><td>202</td><td>92</td><td>148</td><td>227</td><td>197</td><td>215</td><td>0</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>42.7%</td><td>40.2%</td><td>50.4%</td><td>52.0%</td><td>27.2%</td><td>50.0%</td><td>44.9%</td><td>45.7%</td><td>56.3%</td><td>%</td></tr>
</table>
<p></p><table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">
<tr><th bgcolor="#EEEEEE" colspan="11">First-Time full-time Undergrads by Academic Standing at END of first YEAR - cohort and pct return 1 year later
<br/><small>ft1yr_retention report generated: 03-OCT-25</small></th></tr>
<tr bgcolor="#EEEEEE"><th>Acad Standing<br/></th><th>Fall 16<br/></th><th>Fall 17<br/></th><th>Fall 18<br/></th><th>Fall 19<br/></th><th>Fall 20<br/></th><th>Fall 21<br/></th><th>Fall 22<br/></th><th>Fall 23<br/></th><th>Fall 24<br/></th><th>Fall 25<br/></th></tr>
<tr align="RIGHT"><td align="LEFT">Good Standing</td><td>984</td><td>921</td><td>825</td><td>666</td><td>429</td><td>463</td><td>707</td><td>753</td><td>680</td><td>869</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>79.9%</td><td>80.2%</td><td>83.4%</td><td>79.7%</td><td>84.1%</td><td>84.2%</td><td>87.0%</td><td>85.5%</td><td>86.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Prob/Disq/Rein</td><td>298</td><td>267</td><td>213</td><td>149</td><td>103</td><td>146</td><td>223</td><td>184</td><td>207</td><td>0</td></tr>

In [10]:
grader.check("q1_3")

q1_3 results: All test cases passed!

<!-- BEGIN QUESTION -->

**Question 1.4:** Use the `prettify()` method to turn the Beautiful Soup parse tree into a nicely formatted string with each HTML tag on its own line. Take a look through it and take note of any tags or attributes you are unfamiliear with. Look up any tags that aren't familiar.

In [12]:
# Print pretty data

'<html>\n <head>\n  <script src="http://www.humboldt.edu/anstud/ga_pine_irp.js" type="text/javascript">\n  </script>\n  <title>\n   First-Time full-time Undergrad Retention 1-year cohorts\n  </title>\n </head>\n <body #ffffff="">\n  <p>\n  </p>\n  <table border="1" cellpadding="5">\n   <tr bgcolor="#EEEEEE">\n    <th colspan="3">\n     First-Time full-time Undergrads (Freshmen) Retention reports\n    </th>\n   </tr>\n   <tr bgcolor="#FFFFEE">\n    <td>\n     Freshmen cohorts\n    </td>\n    <td>\n     <a href="filter.pl?relevant=ft1term_retention.out">\n      1-term retention\n     </a>\n     <a href="filter.pl?relevant=ft1yr_retention.out">\n      1-year retention\n     </a>\n     <a href="filter.pl?relevant=ft2yr_retention.out">\n      2-year retention\n     </a>\n     <a href="filter.pl?relevant=ft3yr_retention.out">\n      3-year retention\n     </a>\n    </td>\n   </tr>\n   <tr bgcolor="#EEEEEE">\n    <td>\n     <a href="filter.pl?relevant=trans1yr_retention_UD.out">\n      Transfer Student Retention reports\n     </a>\n    </td>\n    <td>\n     <a href="https://ie.humboldt.edu/grad-reten">\n      Return to Graduation and Retention data\n     </a>\n    </td>\n   </tr>\n  </table>\n  <center>\n   <h2>\n    First-Time full-time Undergrad 1-year Retention - Fall Cohorts 2016 - 2025\n   </h2>\n  </center>\n  <p>\n  </p>\n  <table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">\n   <tr>\n    <th bgcolor="#EEEEEE" colspan="11">\n     Overall 1-Year Retention of First-Time full-time Undergrads\n     <br/>\n     <small>\n      ft1yr_retention report generated: 03-OCT-25\n     </small>\n    </th>\n   </tr>\n   <tr bgcolor="#EEEEEE">\n    <th>\n     <br/>\n    </th>\n    <th>\n     Fall 16\n     <br/>\n    </th>\n    <th>\n     Fall 17\n     <br/>\n    </th>\n    <th>\n     Fall 18\n     <br/>\n    </th>\n    <th>\n     Fall 19\n     <br/>\n    </th>\n    <th>\n     Fall 20\n     <br/>\n    </th>\n    <th>\n     Fall 21\n     <br/>\n    </th>\n    <th>\n     Fall 22\n     <br/>\n    </th>\n    <th>\n     Fall 23\n     <br/>\n    </th>\n    <th>\n     Fall 24\n     <br/>\n    </th>\n    <th>\n     Fall 25\n     <br/>\n    </th>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     Initial Cohort\n    </td>\n    <td>\n     1282\n    </td>\n    <td>\n     1188\n    </td>\n    <td>\n     1038\n    </td>\n    <td>\n     815\n    </td>\n    <td>\n     532\n    </td>\n    <td>\n     609\n    </td>\n    <td>\n     930\n    </td>\n    <td>\n     937\n    </td>\n    <td>\n     887\n    </td>\n    <td>\n     869\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     Returned 1-year later\n    </td>\n    <td>\n     879\n    </td>\n    <td>\n     846\n    </td>\n    <td>\n     774\n    </td>\n    <td>\n     596\n    </td>\n    <td>\n     392\n    </td>\n    <td>\n     451\n    </td>\n    <td>\n     703\n    </td>\n    <td>\n     712\n    </td>\n    <td>\n     685\n    </td>\n    <td>\n     0\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     Percent Returning\n    </td>\n    <td>\n     68.6%\n    </td>\n    <td>\n     71.2%\n    </td>\n    <td>\n     74.6%\n    </td>\n    <td>\n     73.1%\n    </td>\n    <td>\n     73.7%\n    </td>\n    <td>\n     74.1%\n    </td>\n    <td>\n     75.6%\n    </td>\n    <td>\n     76.0%\n    </td>\n    <td>\n     77.2%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n  </table>\n  <p>\n  </p>\n  <table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">\n   <tr>\n    <th bgcolor="#EEEEEE" colspan="11">\n     First-Time full-time Undergrads by Sex - cohort and pct return 1 year later\n     <br/>\n     <small>\n      ft1yr_retention report generated: 03-OCT-25\n     </small>\n    </th>\n   </tr>\n   <tr bgcolor="#EEEEEE">\n    <th>\n     Sex\n     <br/>\n    </th>\n    <th>\n     Fall 16\n     <br/>\n    </th>\n    <th>\n     Fall 17\n     <br/>\n    </th>\n    <th>\n     Fall 18\n     <br/>\n    </th>\n    <th>\n     Fall 19\n     <br/>\n    </th>\n    <th>\n     Fall 20\n     <br/>\n    </th>\n    <th>\n     Fall 21\n     <br/>\n    </th>\n    <th>\n     Fall 22\n     <br/>\n    </th>\n    <th>\n     Fall 23\n     <br/>\n    </th>\n    <th>\n     Fall 24\n     <br/>\n    </th>\n    <th>\n     Fall 25\n     <br/>\n    </th>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     F\n    </td>\n    <td>\n     728\n    </td>\n    <td>\n     749\n    </td>\n    <td>\n     603\n    </td>\n    <td>\n     476\n    </td>\n    <td>\n     321\n    </td>\n    <td>\n     352\n    </td>\n    <td>\n     513\n    </td>\n    <td>\n     491\n    </td>\n    <td>\n     447\n    </td>\n    <td>\n     385\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     71.8%\n    </td>\n    <td>\n     74.4%\n    </td>\n    <td>\n     76.8%\n    </td>\n    <td>\n     74.2%\n    </td>\n    <td>\n     75.7%\n    </td>\n    <td>\n     75.3%\n    </td>\n    <td>\n     77.6%\n    </td>\n    <td>\n     77.4%\n    </td>\n    <td>\n     76.1%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     M\n    </td>\n    <td>\n     551\n    </td>\n    <td>\n     433\n    </td>\n    <td>\n     432\n    </td>\n    <td>\n     331\n    </td>\n    <td>\n     204\n    </td>\n    <td>\n     244\n    </td>\n    <td>\n     392\n    </td>\n    <td>\n     426\n    </td>\n    <td>\n     423\n    </td>\n    <td>\n     399\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     64.2%\n    </td>\n    <td>\n     65.8%\n    </td>\n    <td>\n     71.5%\n    </td>\n    <td>\n     71.6%\n    </td>\n    <td>\n     69.6%\n    </td>\n    <td>\n     70.9%\n    </td>\n    <td>\n     73.2%\n    </td>\n    <td>\n     74.9%\n    </td>\n    <td>\n     78.5%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     N\n    </td>\n    <td>\n     3\n    </td>\n    <td>\n     6\n    </td>\n    <td>\n     3\n    </td>\n    <td>\n     6\n    </td>\n    <td>\n     7\n    </td>\n    <td>\n     13\n    </td>\n    <td>\n     25\n    </td>\n    <td>\n     20\n    </td>\n    <td>\n     17\n    </td>\n    <td>\n     60\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     66.7%\n    </td>\n    <td>\n     66.7%\n    </td>\n    <td>\n     66.7%\n    </td>\n    <td>\n     83.3%\n    </td>\n    <td>\n     100.0%\n    </td>\n    <td>\n     100.0%\n    </td>\n    <td>\n     72.0%\n    </td>\n    <td>\n     65.0%\n    </td>\n    <td>\n     76.5%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     U\n    </td>\n    <td>\n     0\n    </td>\n    <td>\n     0\n    </td>\n    <td>\n     0\n    </td>\n    <td>\n     2\n    </td>\n    <td>\n     0\n    </td>\n    <td>\n     0\n    </td>\n    <td>\n     0\n    </td>\n    <td>\n     0\n    </td>\n    <td>\n     0\n    </td>\n    <td>\n     25\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     %\n    </td>\n    <td>\n     %\n    </td>\n    <td>\n     %\n    </td>\n    <td>\n     50.0%\n    </td>\n    <td>\n     %\n    </td>\n    <td>\n     %\n    </td>\n    <td>\n     %\n    </td>\n    <td>\n     %\n    </td>\n    <td>\n     %\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n  </table>\n  <p>\n  </p>\n  <table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">\n   <tr>\n    <th bgcolor="#EEEEEE" colspan="11">\n     First-Time full-time Undergrads by URM - cohort and pct return 1 year later\n     <br/>\n     <small>\n      ft1yr_retention report generated: 03-OCT-25\n     </small>\n    </th>\n   </tr>\n   <tr bgcolor="#EEEEEE">\n    <th>\n     URM\n     <br/>\n    </th>\n    <th>\n     Fall 16\n     <br/>\n    </th>\n    <th>\n     Fall 17\n     <br/>\n    </th>\n    <th>\n     Fall 18\n     <br/>\n    </th>\n    <th>\n     Fall 19\n     <br/>\n    </th>\n    <th>\n     Fall 20\n     <br/>\n    </th>\n    <th>\n     Fall 21\n     <br/>\n    </th>\n    <th>\n     Fall 22\n     <br/>\n    </th>\n    <th>\n     Fall 23\n     <br/>\n    </th>\n    <th>\n     Fall 24\n     <br/>\n    </th>\n    <th>\n     Fall 25\n     <br/>\n    </th>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     Not URM\n    </td>\n    <td>\n     532\n    </td>\n    <td>\n     476\n    </td>\n    <td>\n     453\n    </td>\n    <td>\n     367\n    </td>\n    <td>\n     243\n    </td>\n    <td>\n     360\n    </td>\n    <td>\n     548\n    </td>\n    <td>\n     534\n    </td>\n    <td>\n     508\n    </td>\n    <td>\n     442\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     71.1%\n    </td>\n    <td>\n     73.7%\n    </td>\n    <td>\n     78.6%\n    </td>\n    <td>\n     72.2%\n    </td>\n    <td>\n     77.0%\n    </td>\n    <td>\n     77.8%\n    </td>\n    <td>\n     79.0%\n    </td>\n    <td>\n     78.5%\n    </td>\n    <td>\n     80.5%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     URM\n    </td>\n    <td>\n     671\n    </td>\n    <td>\n     645\n    </td>\n    <td>\n     540\n    </td>\n    <td>\n     401\n    </td>\n    <td>\n     274\n    </td>\n    <td>\n     232\n    </td>\n    <td>\n     357\n    </td>\n    <td>\n     370\n    </td>\n    <td>\n     346\n    </td>\n    <td>\n     399\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     65.1%\n    </td>\n    <td>\n     69.3%\n    </td>\n    <td>\n     71.7%\n    </td>\n    <td>\n     74.3%\n    </td>\n    <td>\n     71.9%\n    </td>\n    <td>\n     68.5%\n    </td>\n    <td>\n     71.7%\n    </td>\n    <td>\n     72.4%\n    </td>\n    <td>\n     72.5%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     Unknown\n    </td>\n    <td>\n     79\n    </td>\n    <td>\n     67\n    </td>\n    <td>\n     45\n    </td>\n    <td>\n     47\n    </td>\n    <td>\n     15\n    </td>\n    <td>\n     17\n    </td>\n    <td>\n     25\n    </td>\n    <td>\n     33\n    </td>\n    <td>\n     33\n    </td>\n    <td>\n     28\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     81.0%\n    </td>\n    <td>\n     71.6%\n    </td>\n    <td>\n     68.9%\n    </td>\n    <td>\n     70.2%\n    </td>\n    <td>\n     53.3%\n    </td>\n    <td>\n     70.6%\n    </td>\n    <td>\n     56.0%\n    </td>\n    <td>\n     75.8%\n    </td>\n    <td>\n     75.8%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n  </table>\n  <p>\n  </p>\n  <table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">\n   <tr>\n    <th bgcolor="#EEEEEE" colspan="11">\n     First-Time full-time Undergrads CSU/IPEDS Ethnicity - cohort and pct return 1 year later\n     <br/>\n     <small>\n      ft1yr_retention report generated: 03-OCT-25\n     </small>\n    </th>\n   </tr>\n   <tr bgcolor="#EEEEEE">\n    <th>\n     CSU/IPEDS Ethnicity\n     <br/>\n    </th>\n    <th>\n     Fall 16\n     <br/>\n    </th>\n    <th>\n     Fall 17\n     <br/>\n    </th>\n    <th>\n     Fall 18\n     <br/>\n    </th>\n    <th>\n     Fall 19\n     <br/>\n    </th>\n    <th>\n     Fall 20\n     <br/>\n    </th>\n    <th>\n     Fall 21\n     <br/>\n    </th>\n    <th>\n     Fall 22\n     <br/>\n    </th>\n    <th>\n     Fall 23\n     <br/>\n    </th>\n    <th>\n     Fall 24\n     <br/>\n    </th>\n    <th>\n     Fall 25\n     <br/>\n    </th>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     African American\n    </td>\n    <td>\n     51\n    </td>\n    <td>\n     57\n    </td>\n    <td>\n     48\n    </td>\n    <td>\n     29\n    </td>\n    <td>\n     23\n    </td>\n    <td>\n     14\n    </td>\n    <td>\n     32\n    </td>\n    <td>\n     20\n    </td>\n    <td>\n     18\n    </td>\n    <td>\n     36\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     64.7%\n    </td>\n    <td>\n     86.0%\n    </td>\n    <td>\n     60.4%\n    </td>\n    <td>\n     72.4%\n    </td>\n    <td>\n     69.6%\n    </td>\n    <td>\n     71.4%\n    </td>\n    <td>\n     71.9%\n    </td>\n    <td>\n     65.0%\n    </td>\n    <td>\n     61.1%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     American Indian\n    </td>\n    <td>\n     11\n    </td>\n    <td>\n     12\n    </td>\n    <td>\n     11\n    </td>\n    <td>\n     7\n    </td>\n    <td>\n     9\n    </td>\n    <td>\n     6\n    </td>\n    <td>\n     8\n    </td>\n    <td>\n     7\n    </td>\n    <td>\n     9\n    </td>\n    <td>\n     13\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     72.7%\n    </td>\n    <td>\n     66.7%\n    </td>\n    <td>\n     81.8%\n    </td>\n    <td>\n     85.7%\n    </td>\n    <td>\n     88.9%\n    </td>\n    <td>\n     66.7%\n    </td>\n    <td>\n     50.0%\n    </td>\n    <td>\n     100.0%\n    </td>\n    <td>\n     55.6%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     Asian American\n    </td>\n    <td>\n     31\n    </td>\n    <td>\n     21\n    </td>\n    <td>\n     22\n    </td>\n    <td>\n     12\n    </td>\n    <td>\n     17\n    </td>\n    <td>\n     15\n    </td>\n    <td>\n     30\n    </td>\n    <td>\n     32\n    </td>\n    <td>\n     23\n    </td>\n    <td>\n     25\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     74.2%\n    </td>\n    <td>\n     71.4%\n    </td>\n    <td>\n     72.7%\n    </td>\n    <td>\n     83.3%\n    </td>\n    <td>\n     70.6%\n    </td>\n    <td>\n     60.0%\n    </td>\n    <td>\n     80.0%\n    </td>\n    <td>\n     93.8%\n    </td>\n    <td>\n     87.0%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     Hispanic/Latino\n    </td>\n    <td>\n     545\n    </td>\n    <td>\n     517\n    </td>\n    <td>\n     444\n    </td>\n    <td>\n     328\n    </td>\n    <td>\n     214\n    </td>\n    <td>\n     190\n    </td>\n    <td>\n     272\n    </td>\n    <td>\n     302\n    </td>\n    <td>\n     275\n    </td>\n    <td>\n     304\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     64.8%\n    </td>\n    <td>\n     67.9%\n    </td>\n    <td>\n     73.0%\n    </td>\n    <td>\n     74.4%\n    </td>\n    <td>\n     71.5%\n    </td>\n    <td>\n     68.4%\n    </td>\n    <td>\n     70.6%\n    </td>\n    <td>\n     72.5%\n    </td>\n    <td>\n     73.8%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     Nonresident Alien\n    </td>\n    <td>\n     18\n    </td>\n    <td>\n     16\n    </td>\n    <td>\n     10\n    </td>\n    <td>\n     6\n    </td>\n    <td>\n     5\n    </td>\n    <td>\n     4\n    </td>\n    <td>\n     5\n    </td>\n    <td>\n     4\n    </td>\n    <td>\n     6\n    </td>\n    <td>\n     4\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     83.3%\n    </td>\n    <td>\n     68.8%\n    </td>\n    <td>\n     60.0%\n    </td>\n    <td>\n     66.7%\n    </td>\n    <td>\n     60.0%\n    </td>\n    <td>\n     75.0%\n    </td>\n    <td>\n     60.0%\n    </td>\n    <td>\n     75.0%\n    </td>\n    <td>\n     83.3%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     Pacific Islander\n    </td>\n    <td>\n     4\n    </td>\n    <td>\n     4\n    </td>\n    <td>\n     5\n    </td>\n    <td>\n     1\n    </td>\n    <td>\n     1\n    </td>\n    <td>\n     1\n    </td>\n    <td>\n     2\n    </td>\n    <td>\n     4\n    </td>\n    <td>\n     3\n    </td>\n    <td>\n     3\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     50.0%\n    </td>\n    <td>\n     50.0%\n    </td>\n    <td>\n     60.0%\n    </td>\n    <td>\n     100.0%\n    </td>\n    <td>\n     100.0%\n    </td>\n    <td>\n     100.0%\n    </td>\n    <td>\n     50.0%\n    </td>\n    <td>\n     75.0%\n    </td>\n    <td>\n     66.7%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     Two or More Races\n    </td>\n    <td>\n     100\n    </td>\n    <td>\n     85\n    </td>\n    <td>\n     53\n    </td>\n    <td>\n     55\n    </td>\n    <td>\n     36\n    </td>\n    <td>\n     40\n    </td>\n    <td>\n     70\n    </td>\n    <td>\n     77\n    </td>\n    <td>\n     74\n    </td>\n    <td>\n     72\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     68.0%\n    </td>\n    <td>\n     69.4%\n    </td>\n    <td>\n     69.8%\n    </td>\n    <td>\n     69.1%\n    </td>\n    <td>\n     72.2%\n    </td>\n    <td>\n     72.5%\n    </td>\n    <td>\n     82.9%\n    </td>\n    <td>\n     77.9%\n    </td>\n    <td>\n     74.3%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     Unknown\n    </td>\n    <td>\n     61\n    </td>\n    <td>\n     51\n    </td>\n    <td>\n     35\n    </td>\n    <td>\n     41\n    </td>\n    <td>\n     10\n    </td>\n    <td>\n     13\n    </td>\n    <td>\n     20\n    </td>\n    <td>\n     29\n    </td>\n    <td>\n     27\n    </td>\n    <td>\n     24\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     80.3%\n    </td>\n    <td>\n     72.5%\n    </td>\n    <td>\n     71.4%\n    </td>\n    <td>\n     70.7%\n    </td>\n    <td>\n     50.0%\n    </td>\n    <td>\n     69.2%\n    </td>\n    <td>\n     55.0%\n    </td>\n    <td>\n     75.9%\n    </td>\n    <td>\n     74.1%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     White\n    </td>\n    <td>\n     461\n    </td>\n    <td>\n     425\n    </td>\n    <td>\n     410\n    </td>\n    <td>\n     336\n    </td>\n    <td>\n     217\n    </td>\n    <td>\n     326\n    </td>\n    <td>\n     491\n    </td>\n    <td>\n     462\n    </td>\n    <td>\n     452\n    </td>\n    <td>\n     388\n    </td>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     <br/>\n    </td>\n    <td>\n     71.1%\n    </td>\n    <td>\n     73.9%\n    </td>\n    <td>\n     79.3%\n    </td>\n    <td>\n     72.3%\n    </td>\n    <td>\n     77.4%\n    </td>\n    <td>\n     78.5%\n    </td>\n    <td>\n     78.8%\n    </td>\n    <td>\n     76.8%\n    </td>\n    <td>\n     80.5%\n    </td>\n    <td>\n     .0%\n    </td>\n   </tr>\n  </table>\n  <p>\n  </p>\n  <table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">\n   <tr>\n    <th bgcolor="#EEEEEE" colspan="12">\n     First-Time full-time Undergrads Sex by URM - cohort and pct return 1 year later\n     <br/>\n     <small>\n      ft1yr_retention report generated: 03-OCT-25\n     </small>\n    </th>\n   </tr>\n   <tr bgcolor="#EEEEEE">\n    <th>\n     Sex\n     <br/>\n    </th>\n    <th>\n     URM\n     <br/>\n    </th>\n    <th>\n     Fall 16\n     <br/>\n    </th>\n    <th>\n     Fall 17\n     <br/>\n    </th>\n    <th>\n     Fall 18\n     <br/>\n    </th>\n    <th>\n     Fall 19\n     <br/>\n    </th>\n    <th>\n     Fall 20\n     <br/>\n    </th>\n    <th>\n     Fall 21\n     <br/>\n    </th>\n    <th>\n     Fall 22\n     <br/>\n    </th>\n    <th>\n     Fall 23\n     <br/>\n    </th>\n    <th>\n     Fall 24\n     <br/>\n    </th>\n    <th>\n     Fall 25\n     <br/>\n    </th>\n   </tr>\n   <tr align="RIGHT">\n    <td align="LEFT">\n     F\n    </td>\n    <td align="LEFT">\n     Not URM\n    </td>\n    <td>\n     277\n    </td>\n    <td>\n     295\

<!-- END QUESTION -->

### 2. Parse and clean the data

**Question 2.1:** Use a BeautifulSoup method to determine how many tables are on the webpage.

In [13]:
num_tables = ...
num_tables

16

In [14]:
grader.check("q2_1")

q2_1 results: All test cases passed!

**Question 2.2:** Access the second to last table and put the contents in `table1_code`. Inspect it, and then give a brief description of what the table contains.

In [15]:
table1_code = ....
table1_code

<table align="CENTER" bgcolor="#FFFFEE" border="1" cellpadding="1" cellspacing="0" width="100%">
<tr><th bgcolor="#EEEEEE" colspan="11">First-Time full-time Undergrads by current Major - cohort and pct return 1 year later
<br/><small>ft1yr_retention report generated: 03-OCT-25</small></th></tr>
<tr bgcolor="#EEEEEE"><th>Major Program<br/></th><th>Fall 16<br/></th><th>Fall 17<br/></th><th>Fall 18<br/></th><th>Fall 19<br/></th><th>Fall 20<br/></th><th>Fall 21<br/></th><th>Fall 22<br/></th><th>Fall 23<br/></th><th>Fall 24<br/></th><th>Fall 25<br/></th></tr>
<tr align="RIGHT"><td align="LEFT">Anthropology</td><td>23</td><td>15</td><td>18</td><td>19</td><td>7</td><td>13</td><td>16</td><td>16</td><td>8</td><td>9</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>73.9%</td><td>86.7%</td><td>83.3%</td><td>57.9%</td><td>100.0%</td><td>76.9%</td><td>75.0%</td><td>87.5%</td><td>87.5%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Applied Fire Science &amp; Mgmt</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>4</td><td>16</td><td>15</td><td>35</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>50.0%</td><td>100.0%</td><td>56.3%</td><td>73.3%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Art</td><td>36</td><td>36</td><td>38</td><td>17</td><td>20</td><td>33</td><td>41</td><td>41</td><td>17</td><td>13</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>75.0%</td><td>72.2%</td><td>65.8%</td><td>70.6%</td><td>80.0%</td><td>81.8%</td><td>80.5%</td><td>75.6%</td><td>76.5%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Art History and Museum Studies</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td><td>3</td><td>2</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>100.0%</td><td>33.3%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Biochemistry</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>18</td><td>15</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>100.0%</td><td>%</td><td>%</td><td>%</td><td>50.0%</td><td>100.0%</td><td>72.2%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Biology</td><td>66</td><td>80</td><td>74</td><td>61</td><td>56</td><td>48</td><td>61</td><td>41</td><td>43</td><td>52</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>72.7%</td><td>68.8%</td><td>70.3%</td><td>68.9%</td><td>67.9%</td><td>66.7%</td><td>62.3%</td><td>92.7%</td><td>79.1%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Botany</td><td>16</td><td>14</td><td>20</td><td>17</td><td>13</td><td>16</td><td>23</td><td>15</td><td>17</td><td>15</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>56.3%</td><td>50.0%</td><td>85.0%</td><td>64.7%</td><td>92.3%</td><td>87.5%</td><td>69.6%</td><td>60.0%</td><td>82.4%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Business Administration</td><td>111</td><td>103</td><td>83</td><td>56</td><td>35</td><td>47</td><td>54</td><td>41</td><td>70</td><td>52</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>63.1%</td><td>75.7%</td><td>79.5%</td><td>85.7%</td><td>71.4%</td><td>80.9%</td><td>77.8%</td><td>68.3%</td><td>80.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">CD &amp; Fam Rel - General</td><td>0</td><td>1</td><td>1</td><td>7</td><td>10</td><td>13</td><td>13</td><td>11</td><td>6</td><td>8</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>92.3%</td><td>76.9%</td><td>81.8%</td><td>83.3%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Cannabis Studies</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>13</td><td>3</td><td>1</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>100.0%</td><td>53.8%</td><td>66.7%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Chemistry</td><td>30</td><td>24</td><td>24</td><td>13</td><td>5</td><td>11</td><td>6</td><td>9</td><td>6</td><td>9</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>60.0%</td><td>50.0%</td><td>79.2%</td><td>92.3%</td><td>100.0%</td><td>63.6%</td><td>83.3%</td><td>66.7%</td><td>66.7%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Communication</td><td>22</td><td>19</td><td>17</td><td>5</td><td>5</td><td>4</td><td>7</td><td>6</td><td>3</td><td>7</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>59.1%</td><td>84.2%</td><td>70.6%</td><td>20.0%</td><td>40.0%</td><td>100.0%</td><td>85.7%</td><td>66.7%</td><td>66.7%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Computer Science</td><td>41</td><td>25</td><td>14</td><td>23</td><td>12</td><td>17</td><td>33</td><td>36</td><td>21</td><td>14</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>61.0%</td><td>60.0%</td><td>78.6%</td><td>78.3%</td><td>58.3%</td><td>64.7%</td><td>81.8%</td><td>83.3%</td><td>66.7%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Criminology &amp; Justice Studies</td><td>65</td><td>57</td><td>38</td><td>32</td><td>17</td><td>18</td><td>17</td><td>20</td><td>22</td><td>21</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>63.1%</td><td>70.2%</td><td>81.6%</td><td>75.0%</td><td>82.4%</td><td>77.8%</td><td>76.5%</td><td>70.0%</td><td>68.2%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Crit Race, Gender &amp; Sexuality</td><td>11</td><td>8</td><td>11</td><td>10</td><td>2</td><td>10</td><td>6</td><td>4</td><td>1</td><td>0</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>72.7%</td><td>75.0%</td><td>100.0%</td><td>90.0%</td><td>.0%</td><td>80.0%</td><td>83.3%</td><td>50.0%</td><td>100.0%</td><td>%</td></tr>
<tr align="RIGHT"><td align="LEFT">Dance</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>1</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>100.0%</td><td>100.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Data Science</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>4</td><td>4</td><td>3</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>.0%</td><td>%</td><td>%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Economics</td><td>9</td><td>3</td><td>8</td><td>3</td><td>4</td><td>2</td><td>6</td><td>5</td><td>2</td><td>2</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>100.0%</td><td>100.0%</td><td>75.0%</td><td>66.7%</td><td>100.0%</td><td>50.0%</td><td>83.3%</td><td>100.0%</td><td>100.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Energy Systems Engineering</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>9</td><td>6</td><td>7</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>100.0%</td><td>88.9%</td><td>83.3%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">English</td><td>28</td><td>27</td><td>25</td><td>19</td><td>9</td><td>11</td><td>14</td><td>19</td><td>10</td><td>17</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>75.0%</td><td>66.7%</td><td>72.0%</td><td>73.7%</td><td>66.7%</td><td>63.6%</td><td>64.3%</td><td>63.2%</td><td>80.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Environmental Managemnt &amp; Prot</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>42.9%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td></tr>
<tr align="RIGHT"><td align="LEFT">Environmental Resources Engr</td><td>39</td><td>28</td><td>25</td><td>19</td><td>13</td><td>6</td><td>23</td><td>17</td><td>24</td><td>20</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>79.5%</td><td>82.1%</td><td>92.0%</td><td>78.9%</td><td>92.3%</td><td>83.3%</td><td>69.6%</td><td>82.4%</td><td>87.5%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Environmental Science</td><td>14</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>35.7%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td></tr>
<tr align="RIGHT"><td align="LEFT">Environmental Science &amp; Mgmt</td><td>67</td><td>57</td><td>58</td><td>39</td><td>14</td><td>28</td><td>60</td><td>51</td><td>34</td><td>34</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>98.5%</td><td>84.2%</td><td>93.1%</td><td>66.7%</td><td>78.6%</td><td>85.7%</td><td>78.3%</td><td>80.4%</td><td>88.2%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Environmental Studies</td><td>28</td><td>21</td><td>27</td><td>22</td><td>7</td><td>8</td><td>19</td><td>12</td><td>11</td><td>8</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>78.6%</td><td>90.5%</td><td>85.2%</td><td>86.4%</td><td>42.9%</td><td>62.5%</td><td>94.7%</td><td>75.0%</td><td>63.6%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Film</td><td>14</td><td>15</td><td>15</td><td>20</td><td>6</td><td>4</td><td>22</td><td>15</td><td>16</td><td>11</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>57.1%</td><td>60.0%</td><td>66.7%</td><td>55.0%</td><td>66.7%</td><td>50.0%</td><td>90.9%</td><td>73.3%</td><td>62.5%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Fine Art, BFA</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>2</td><td>2</td><td>4</td><td>0</td><td>0</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>100.0%</td><td>%</td><td>%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>%</td><td>%</td></tr>
<tr align="RIGHT"><td align="LEFT">Fisheries Biology</td><td>14</td><td>12</td><td>10</td><td>11</td><td>4</td><td>8</td><td>13</td><td>16</td><td>15</td><td>11</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>71.4%</td><td>66.7%</td><td>90.0%</td><td>72.7%</td><td>75.0%</td><td>62.5%</td><td>92.3%</td><td>81.3%</td><td>66.7%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Forestry</td><td>32</td><td>28</td><td>34</td><td>30</td><td>26</td><td>26</td><td>43</td><td>46</td><td>46</td><td>41</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>59.4%</td><td>53.6%</td><td>70.6%</td><td>63.3%</td><td>92.3%</td><td>65.4%</td><td>62.8%</td><td>65.2%</td><td>87.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">French</td><td>0</td><td>4</td><td>1</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>75.0%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td></tr>
<tr align="RIGHT"><td align="LEFT">Geography</td><td>8</td><td>5</td><td>4</td><td>5</td><td>0</td><td>2</td><td>2</td><td>1</td><td>2</td><td>4</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>75.0%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Geology</td><td>11</td><td>8</td><td>10</td><td>9</td><td>3</td><td>3</td><td>17</td><td>12</td><td>5</td><td>6</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>63.6%</td><td>75.0%</td><td>100.0%</td><td>77.8%</td><td>100.0%</td><td>100.0%</td><td>88.2%</td><td>83.3%</td><td>80.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Geospatial Science &amp; Tech</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>2</td><td>4</td><td>3</td><td>3</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>%</td><td>.0%</td><td>%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">History</td><td>25</td><td>20</td><td>19</td><td>16</td><td>9</td><td>10</td><td>12</td><td>13</td><td>8</td><td>7</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>76.0%</td><td>70.0%</td><td>78.9%</td><td>68.8%</td><td>77.8%</td><td>70.0%</td><td>75.0%</td><td>76.9%</td><td>87.5%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">IS - Crit Race, Gen &amp; Sex</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>.0%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td></tr>
<tr align="RIGHT"><td align="LEFT">IS - Dance Studies</td><td>6</td><td>3</td><td>1</td><td>1</td><td>1</td><td>8</td><td>2</td><td>1</td><td>0</td><td>0</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>83.3%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>87.5%</td><td>100.0%</td><td>100.0%</td><td>%</td><td>%</td></tr>
<tr align="RIGHT"><td align="LEFT">Interdisciplinary Studies</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>1</td><td>6</td><td>5</td><td>4</td><td>5</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>50.0%</td><td>%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>75.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">International Studies</td><td>8</td><td>14</td><td>5</td><td>9</td><td>5</td><td>0</td><td>4</td><td>2</td><td>0</td><td>0</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>87.5%</td><td>78.6%</td><td>60.0%</td><td>88.9%</td><td>80.0%</td><td>%</td><td>75.0%</td><td>50.0%</td><td>%</td><td>%</td></tr>
<tr align="RIGHT"><td align="LEFT">Journalism</td><td>21</td><td>23</td><td>7</td><td>9</td><td>9</td><td>13</td><td>11</td><td>8</td><td>6</td><td>6</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>61.9%</td><td>69.6%</td><td>71.4%</td><td>77.8%</td><td>44.4%</td><td>61.5%</td><td>72.7%</td><td>100.0%</td><td>100.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Kinesiology</td><td>92</td><td>69</td><td>42</td><td>37</td><td>33</td><td>27</td><td>41</td><td>35</td><td>52</td><td>33</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>58.7%</td><td>69.6%</td><td>69.0%</td><td>78.4%</td><td>69.7%</td><td>66.7%</td><td>82.9%</td><td>71.4%</td><td>71.2%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Liberal St-Child Dev-Elem Ed</td><td>1</td><td>2</td><td>2</td><td>2</td><td>2</td><td>2</td><td>6</td><td>1</td><td>2</td><td>2</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>.0%</td><td>50.0%</td><td>.0%</td><td>100.0%</td><td>100.0%</td><td>100.0%</td><td>83.3%</td><td>100.0%</td><td>50.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Liberal Studies-Child Develop</td><td>32</td><td>21</td><td>13</td><td>11</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>65.6%</td><td>66.7%</td><td>84.6%</td><td>90.9%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td></tr>
<tr align="RIGHT"><td align="LEFT">Liberal Studies-Elementary Ed</td><td>27</td><td>28</td><td>17</td><td>10</td><td>11</td><td>14</td><td>10</td><td>11</td><td>19</td><td>17</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>81.5%</td><td>78.6%</td><td>70.6%</td><td>60.0%</td><td>90.9%</td><td>78.6%</td><td>90.0%</td><td>81.8%</td><td>78.9%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Liberal Studies-Recreation Adm</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>.0%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td></tr>
<tr align="RIGHT"><td align="LEFT">Marine Biology</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>14</td><td>34</td><td>36</td><td>49</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>%</td><td>100.0%</td><td>%</td><td>100.0%</td><td>73.5%</td><td>75.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Mathematics</td><td>11</td><td>16</td><td>13</td><td>6</td><td>5</td><td>5</td><td>10</td><td>6</td><td>11</td><td>5</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>81.8%</td><td>68.8%</td><td>69.2%</td><td>83.3%</td><td>80.0%</td><td>60.0%</td><td>80.0%</td><td>100.0%</td><td>81.8%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Mechanical Engineering</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>12</td><td>53</td><td>64</td><td>57</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>100.0%</td><td>91.7%</td><td>81.1%</td><td>76.6%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Media Arts, BFA</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Music</td><td>19</td><td>19</td><td>8</td><td>5</td><td>2</td><td>8</td><td>4</td><td>8</td><td>10</td><td>6</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>57.9%</td><td>84.2%</td><td>87.5%</td><td>100.0%</td><td>100.0%</td><td>75.0%</td><td>100.0%</td><td>62.5%</td><td>50.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Native American Studies</td><td>1</td><td>3</td><td>4</td><td>2</td><td>1</td><td>5</td><td>4</td><td>3</td><td>1</td><td>1</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>100.0%</td><td>33.3%</td><td>75.0%</td><td>50.0%</td><td>100.0%</td><td>80.0%</td><td>100.0%</td><td>66.7%</td><td>.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Oceanography</td><td>10</td><td>9</td><td>10</td><td>10</td><td>3</td><td>5</td><td>9</td><td>9</td><td>6</td><td>3</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>60.0%</td><td>88.9%</td><td>80.0%</td><td>60.0%</td><td>100.0%</td><td>80.0%</td><td>55.6%</td><td>100.0%</td><td>66.7%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Philosophy</td><td>9</td><td>5</td><td>5</td><td>1</td><td>2</td><td>6</td><td>5</td><td>2</td><td>2</td><td>3</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>55.6%</td><td>80.0%</td><td>80.0%</td><td>100.0%</td><td>.0%</td><td>100.0%</td><td>100.0%</td><td>50.0%</td><td>50.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Physical Science</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>%</td><td>100.0%</td><td>%</td></tr>
<tr align="RIGHT"><td align="LEFT">Physics</td><td>17</td><td>12</td><td>5</td><td>5</td><td>6</td><td>4</td><td>11</td><td>10</td><td>12</td><td>9</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>70.6%</td><td>91.7%</td><td>100.0%</td><td>80.0%</td><td>66.7%</td><td>100.0%</td><td>63.6%</td><td>90.0%</td><td>50.0%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Political Science</td><td>27</td><td>30</td><td>28</td><td>17</td><td>7</td><td>9</td><td>9</td><td>15</td><td>13</td><td>11</td></tr>
<tr align="RIGHT"><td align="LEFT"><br/></td><td>66.7%</td><td>70.0%</td><td>71.4%</td><td>94.1%</td><td>42.9%</td><td>88.9%</td><td>66.7%</td><td>66.7%</td><td>92.3%</td><td>.0%</td></tr>
<tr align="RIGHT"><td align="LEFT">Psychology</td><td>110</td><td>102</td><td>81</td><td>54</td><td>52</td><td>44</td><td>79</td><td>77</td><td>55</td><td>51</td></tr>

In [16]:
grader.check("q2_2")

q2_2 results: All test cases passed!

**Question 2.3:** Put the contents from the second to last table (`table1_code`) into Pandas Data Frame.

*HINT 1:* You will probably find it helpful to first create a nested list of the data. Each inner list should contain the contents of one row in the table. The outer list should contain all the rows. Use this nested list to create the Pandas DataFrame.

*HINT 2:* Notice that the first two rows in the table have headers (a slightly different structure from the rest of the table). You might find it helpful to first create the data frame to contain the body of the table. Then create the column names with the headers afterward. That is, find the table headers with `.find_all('th')`

table1_df

In [32]:
# Create a nested list of data

nested_list = []

.....

    
nested_list

[[],
 [],
 ['Anthropology', '23', '15', '18', '19', '7', '13', '16', '16', '8', '9'],
 ['',
  '73.9%',
  '86.7%',
  '83.3%',
  '57.9%',
  '100.0%',
  '76.9%',
  '75.0%',
  '87.5%',
  '87.5%',
  '.0%'],
 ['Applied Fire Science & Mgmt',
  '0',
  '0',
  '0',
  '0',
  '0',
  '2',
  '4',
  '16',
  '15',
  '35'],
 ['', '%', '%', '%', '%', '%', '50.0%', '100.0%', '56.3%', '73.3%', '.0%'],
 ['Art', '36', '36', '38', '17', '20', '33', '41', '41', '17', '13'],
 ['',
  '75.0%',
  '72.2%',
  '65.8%',
  '70.6%',
  '80.0%',
  '81.8%',
  '80.5%',
  '75.6%',
  '76.5%',
  '.0%'],
 ['Art History and Museum Studies',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '6',
  '3',
  '2'],
 ['', '%', '%', '%', '%', '%', '%', '%', '100.0%', '33.3%', '.0%'],
 ['Biochemistry', '0', '0', '1', '0', '0', '0', '4', '4', '18', '15'],
 ['', '%', '%', '100.0%', '%', '%', '%', '50.0%', '100.0%', '72.2%', '.0%'],
 ['Biology', '66', '80', '74', '61', '56', '48', '61', '41', '43', '52'],
 ['',
  '72.7%',
  '68.8%',
  '70.3%',
  '68.9%',
  '67.9%',
  '66.7%',
  '62.3%',
  '92.7%',
  '79.1%',
  '.0%'],
 ['Botany', '16', '14', '20', '17', '13', '16', '23', '15', '17', '15'],
 ['',
  '56.3%',
  '50.0%',
  '85.0%',
  '64.7%',
  '92.3%',
  '87.5%',
  '69.6%',
  '60.0%',
  '82.4%',
  '.0%'],
 ['Business Administration',
  '111',
  '103',
  '83',
  '56',
  '35',
  '47',
  '54',
  '41',
  '70',
  '52'],
 ['',
  '63.1%',
  '75.7%',
  '79.5%',
  '85.7%',
  '71.4%',
  '80.9%',
  '77.8%',
  '68.3%',
  '80.0%',
  '.0%'],
 ['CD & Fam Rel - General',
  '0',
  '1',
  '1',
  '7',
  '10',
  '13',
  '13',
  '11',
  '6',
  '8'],
 ['',
  '%',
  '100.0%',
  '100.0%',
  '100.0%',
  '100.0%',
  '92.3%',
  '76.9%',
  '81.8%',
  '83.3%',
  '.0%'],
 ['Cannabis Studies', '0', '0', '0', '0', '0', '0', '2', '13', '3', '1'],
 ['', '%', '%', '%', '%', '%', '%', '100.0%', '53.8%', '66.7%', '.0%'],
 ['Chemistry', '30', '24', '24', '13', '5', '11', '6', '9', '6', '9'],
 ['',
  '60.0%',
  '50.0%',
  '79.2%',
  '92.3%',
  '100.0%',
  '63.6%',
  '83.3%',
  '66.7%',
  '66.7%',
  '.0%'],
 ['Communication', '22', '19', '17', '5', '5', '4', '7', '6', '3', '7'],
 ['',
  '59.1%',
  '84.2%',
  '70.6%',
  '20.0%',
  '40.0%',
  '100.0%',
  '85.7%',
  '66.7%',
  '66.7%',
  '.0%'],
 ['Computer Science',
  '41',
  '25',
  '14',
  '23',
  '12',
  '17',
  '33',
  '36',
  '21',
  '14'],
 ['',
  '61.0%',
  '60.0%',
  '78.6%',
  '78.3%',
  '58.3%',
  '64.7%',
  '81.8%',
  '83.3%',
  '66.7%',
  '.0%'],
 ['Criminology & Justice Studies',
  '65',
  '57',
  '38',
  '32',
  '17',
  '18',
  '17',
  '20',
  '22',
  '21'],
 ['',
  '63.1%',
  '70.2%',
  '81.6%',
  '75.0%',
  '82.4%',
  '77.8%',
  '76.5%',
  '70.0%',
  '68.2%',
  '.0%'],
 ['Crit Race, Gender & Sexuality',
  '11',
  '8',
  '11',
  '10',
  '2',
  '10',
  '6',
  '4',
  '1',
  '0'],
 ['',
  '72.7%',
  '75.0%',
  '100.0%',
  '90.0%',
  '.0%',
  '80.0%',
  '83.3%',
  '50.0%',
  '100.0%',
  '%'],
 ['Dance', '0', '0', '0', '0', '0', '0', '0', '1', '1', '1'],
 ['', '%', '%', '%', '%', '%', '%', '%', '100.0%', '100.0%', '.0%'],
 ['Data Science', '0', '0', '0', '1', '0', '0', '1', '4', '4', '3'],
 ['', '%', '%', '%', '.0%', '%', '%', '100.0%', '100.0%', '100.0%', '.0%'],
 ['Economics', '9', '3', '8', '3', '4', '2', '6', '5', '2', '2'],
 ['',
  '100.0%',
  '100.0%',
  '75.0%',
  '66.7%',
  '100.0%',
  '50.0%',
  '83.3%',
  '100.0%',
  '100.0%',
  '.0%'],
 ['Energy Systems Engineering',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '2',
  '9',
  '6',
  '7'],
 ['', '%', '%', '%', '%', '%', '%', '100.0%', '88.9%', '83.3%', '.0%'],
 ['English', '28', '27', '25', '19', '9', '11', '14', '19', '10', '17'],
 ['',
  '75.0%',
  '66.7%',
  '72.0%',
  '73.7%',
  '66.7%',
  '63.6%',
  '64.3%',
  '63.2%',
  '80.0%',
  '.0%'],
 ['Environmental Managemnt & Prot',
  '7',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 ['', '42.9%', '%', '%', '%', '%', '%', '%', '%', '%', '%'],
 ['Environmental Resources Engr',
  '39',
  '28',
  '25',
  '19',
  '13',
  '6',
  '23',
  '17',
  '24',
  '20'],
 ['',
  '79.5%',
  '82.1%',
  '92.0%',
  '78.9%',
  '92.3%',
  '83.3%',
  '69.6%',
  '82.4%',
  '87.5%',
  '.0%'],
 ['Environmental Science', '14', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
 ['', '35.7%', '%', '%', '%', '%', '%', '%', '%', '%', '%'],
 ['Environmental Science & Mgmt',
  '67',
  '57',
  '58',
  '39',
  '14',
  '28',
  '60',
  '51',
  '34',
  '34'],
 ['',
  '98.5%',
  '84.2%',
  '93.1%',
  '66.7%',
  '78.6%',
  '85.7%',
  '78.3%',
  '80.4%',
  '88.2%',
  '.0%'],
 ['Environmental Studies',
  '28',
  '21',
  '27',
  '22',
  '7',
  '8',
  '19',
  '12',
  '11',
  '8'],
 ['',
  '78.6%',
  '90.5%',
  '85.2%',
  '86.4%',
  '42.9%',
  '62.5%',
  '94.7%',
  '75.0%',
  '63.6%',
  '.0%'],
 ['Film', '14', '15', '15', '20', '6', '4', '22', '15', '16', '11'],
 ['',
  '57.1%',
  '60.0%',
  '66.7%',
  '55.0%',
  '66.7%',
  '50.0%',
  '90.9%',
  '73.3%',
  '62.5%',
  '.0%'],
 ['Fine Art, BFA', '0', '0', '4', '0', '0', '2', '2', '4', '0', '0'],
 ['', '%', '%', '100.0%', '%', '%', '100.0%', '100.0%', '100.0%', '%', '%'],
 ['Fisheries Biology',
  '14',
  '12',
  '10',
  '11',
  '4',
  '8',
  '13',
  '16',
  '15',
  '11'],
 ['',
  '71.4%',
  '66.7%',
  '90.0%',
  '72.7%',
  '75.0%',
  '62.5%',
  '92.3%',
  '81.3%',
  '66.7%',
  '.0%'],
 ['Forestry', '32', '28', '34', '30', '26', '26', '43', '46', '46', '41'],
 ['',
  '59.4%',
  '53.6%',
  '70.6%',
  '63.3%',
  '92.3%',
  '65.4%',
  '62.8%',
  '65.2%',
  '87.0%',
  '.0%'],
 ['French', '0', '4', '1', '2', '1', '0', '0', '0', '0', '0'],
 ['', '%', '75.0%', '100.0%', '100.0%', '100.0%', '%', '%', '%', '%', '%'],
 ['Geography', '8', '5', '4', '5', '0', '2', '2', '1', '2', '4'],
 ['',
  '75.0%',
  '100.0%',
  '100.0%',
  '100.0%',
  '%',
  '100.0%',
  '100.0%',
  '100.0%',
  '100.0%',
  '.0%'],
 ['Geology', '11', '8', '10', '9', '3', '3', '17', '12', '5', '6'],
 ['',
  '63.6%',
  '75.0%',
  '100.0%',
  '77.8%',
  '100.0%',
  '100.0%',
  '88.2%',
  '83.3%',
  '80.0%',
  '.0%'],
 ['Geospatial Science & Tech',
  '0',
  '0',
  '0',
  '0',
  '1',
  '0',
  '2',
  '4',
  '3',
  '3'],
 ['', '%', '%', '%', '%', '.0%', '%', '100.0%', '100.0%', '100.0%', '.0%'],
 ['History', '25', '20', '19', '16', '9', '10', '12', '13', '8', '7'],
 ['',
  '76.0%',
  '70.0%',
  '78.9%',
  '68.8%',
  '77.8%',
  '70.0%',
  '75.0%',
  '76.9%',
  '87.5%',
  '.0%'],
 ['IS - Crit Race, Gen & Sex',
  '0',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 ['', '%', '.0%', '%', '%', '%', '%', '%', '%', '%', '%'],
 ['IS - Dance Studies', '6', '3', '1', '1', '1', '8', '2', '1', '0', '0'],
 ['',
  '83.3%',
  '100.0%',
  '100.0%',
  '100.0%',
  '100.0%',
  '87.5%',
  '100.0%',
  '100.0%',
  '%',
  '%'],
 ['Interdisciplinary Studies',
  '0',
  '0',
  '0',
  '2',
  '0',
  '1',
  '6',
  '5',
  '4',
  '5'],
 ['',
  '%',
  '%',
  '%',
  '50.0%',
  '%',
  '100.0%',
  '100.0%',
  '100.0%',
  '75.0%',
  '.0%'],
 ['International Studies', '8', '14', '5', '9', '5', '0', '4', '2', '0', '0'],
 ['',
  '87.5%',
  '78.6%',
  '60.0%',
  '88.9%',
  '80.0%',
  '%',
  '75.0%',
  '50.0%',
  '%',
  '%'],
 ['Journalism', '21', '23', '7', '9', '9', '13', '11', '8', '6', '6'],
 ['',
  '61.9%',
  '69.6%',
  '71.4%',
  '77.8%',
  '44.4%',
  '61.5%',
  '72.7%',
  '100.0%',
  '100.0%',
  '.0%'],
 ['Kinesiology', '92', '69', '42', '37', '33', '27', '41', '35', '52', '33'],
 ['',
  '58.7%',
  '69.6%',
  '69.0%',
  '78.4%',
  '69.7%',
  '66.7%',
  '82.9%',
  '71.4%',
  '71.2%',
  '.0%'],
 ['Liberal St-Child Dev-Elem Ed',
  '1',
  '2',
  '2',
  '2',
  '2',
  '2',
  '6',
  '1',
  '2',
  '2'],
 ['',
  '.0%',
  '50.0%',
  '.0%',
  '100.0%',
  '100.0%',
  '100.0%',
  '83.3%',
  '100.0%',
  '50.0%',
  '.0%'],
 ['Liberal Studies-Child Develop',
  '32',
  '21',
  '13',
  '11',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 ['', '65.6%', '66.7%', '84.6%', '90.9%', '%', '%', '%', '%', '%', '%'],
 ['Liberal Studies-Elementary Ed',
  '27',
  '28',
  '17',
  '10',
  '11',
  '14',
  '10',
  '11',
  '19',
  '17'],
 ['',
  '81.5%',
  '78.6%',
  '70.6%',
  '60.0%',
  '90.9%',
  '78.6%',
  '90.0%',
  '81.8%',
  '78.9%',
  '.0%'],
 ['Liberal Studies-Recreation Adm',
  '0',
  '0',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 ['', '%', '%', '.0%', '%', '%', '%', '%', '%', '%', '%'],
 ['Marine Biology', '0', '0', '0', '0', '1', '0', '14', '34', '36', '49'],
 ['', '%', '%', '%', '%', '100.0%', '%', '100.0%', '73.5%', '75.0%', '.0%'],
 ['Mathematics', '11', '16', '13', '6', '5', '5', '10', '6', '11', '5'],
 ['',
  '81.8%',
  '68.8%',
  '69.2%',
  '83.3%',
  '80.0%',
  '60.0%',
  '80.0%',
  '100.0%',
  '81.8%',
  '.0%'],
 ['Mechanical Engineering',
  '0',
  '0',
  '0',
  '0',
  '0',
  '2',
  '12',
  '53',
  '64',
  '57'],
 ['', '%', '%', '%', '%', '%', '100.0%', '91.7%', '81.1%', '76.6%', '.0%'],
 ['Media Arts, BFA', '0', '0', '0', '0', '0', '0', '0', '0', '0', '4'],
 ['', '%', '%', '%', '%', '%', '%', '%', '%', '%', '.0%'],
 ['Music', '19', '19', '8', '5', '2', '8', '4', '8', '10', '6'],
 ['',
  '57.9%',
  '84.2%',
  '87.5%',
  '100.0%',
  '100.0%',
  '75.0%',
  '100.0%',
  '62.5%',
  '50.0%',
  '.0%'],
 ['Native American Studies', '1', '3', '4', '2', '1', '5', '4', '3', '1', '1'],
 ['',
  '100.0%',
  '33.3%',
  '75.0%',
  '50.0%',
  '100.0%',
  '80.0%',
  '100.0%',
  '66.7%',
  '.0%',
  '.0%'],
 ['Oceanography', '10', '9', '10', '10', '3', '5', '9', '9', '6', '3'],
 ['',
  '60.0%',
  '88.9%',
  '80.0%',
  '60.0%',
  '100.0%',
  '80.0%',
  '55.6%',
  '100.0%',
  '66.7%',
  '.0%'],
 ['Philosophy', '9', '5', '5', '1', '2', '6', '5', '2', '2', '3'],
 ['',
  '55.6%',
  '80.0%',
  '80.0%',
  '100.0%',
  '.0%',
  '100.0%',
  '100.0%',
  '50.0%',
  '50.0%',
  '.0%'],
 ['Physical Science', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'],
 ['', '%', '%', '%', '%', '%', '%', '%', '%', '100.0%', '%'],
 ['Physics', '17', '12', '5', '5', '6', '4', '11', '10', '12', '9'],
 ['',
  '70.6%',
  '91.7%',
  '100.0%',
  '80.0%',
  '66.7%',
  '100.0%',
  '63.6%',
  '90.0%',
  '50.0%',
  '.0%'],
 ['Political Science',
  '27',
  '30',
  '28',
  '17',
  '7',
  '9',
  '9',
  '15',
  '13',
  '11'],
 ['',
  '66.7%',
  '70.0%',
  '71.4%',
  '94.1%',
  '42.9%',
  '88.9%',
  '66.7%',
  '66.7%',
  '92.3%',
  '.0%'],
 ['Psychology', '110', '102', '81', '54', '52', '44', '79', '77', '55', '51'],
 ['',
  '74.5%',
  '75.5%',
  '70.4%',
  '79.6%',
  '71.2%',
  '68.2%',
  '70.9%',
  '76.6%',
  '72.7%',
  '.0%'],
 ['Rangeland Resource Science',
  '7',
  '1',
  '4',
  '3',
  '3',
  '2',
  '3',
  '2',
  '7',
  '4'],
 ['',
  '85.7%',
  '100.0%',
  '100.0%',
  '100.0%',
  '66.7%',
  '100.0%',
  '100.0%',
  '100.0%',
  '100.0%',
  '.0%'],
 ['Recreation Administration',
  '11',
  '21',
  '7',
  '4',
  '1',
  '7',
  '4',
  '8',
  '1',
  '2'],
 ['',
  '100.0%',
  '76.2%',
  '71.4%',
  '100.0%',
  '100.0%',
  '100.0%',
  '75.0%',
  '87.5%',
  '.0%',
  '.0%'],
 ['Religious Studies', '3', '5', '6', '0', '0', '1', '1', '4', '0', '0'],
 ['',
  '100.0%',
  '80.0%',
  '100.0%',
  '%',
  '%',
  '100.0%',
  '100.0%',
  '75.0%',
  '%',
  '%'],
 ['Social Work', '27', '32', '28', '16', '12', '14', '11', '8', '8', '6'],
 ['',
  '66.7%',
  '84.4%',
  '82.1%',
  '87.5%',
  '75.0%',
  '85.7%',
  '90.9%',
  '100.0%',
  '87.5%',
  '.0%'],
 ['Sociology', '9', '15', '13', '5', '3', '9', '6', '7', '5', '2'],
 ['',
  '44.4%',
  '60.0%',
  '61.5%',
  '60.0%',
  '100.0%',
  '88.9%',
  '83.3%',
  '71.4%',
  '100.0%',
  '.0%'],
 ['Software Engineering', '0', '0', '0', '0', '0', '0', '1', '11', '8', '5'],
 ['', '%', '%', '%', '%', '%', '%', '100.0%', '90.9%', '75.0%', '.0%'],
 ['Spanish', '4', '4', '5', '1', '0', '0', '2', '1', '1', '2'],
 ['',
  '75.0%',
  '100.0%',
  '40.0%',
  '100.0%',
  '%',
  '%',
  '100.0%',
  '.0%',
  '.0%',
  '.0%'],
 ['Theatre Arts', '7', '8', '8', '6', '5', '8', '13', '8', '2', '8'],
 ['',
  '85.7%',
  '87.5%',
  '62.5%',
  '83.3%',
  '80.0%',
  '62.5%',
  '53.8%',
  '75.0%',
  '100.0%',
  '.0%'],
 ['Undeclared', '61', '62', '71', '57', '27', '20', '37', '28', '27', '40'],
 ['',
  '39.3%',
  '35.5%',
  '38.0%',
  '50.9%',
  '33.3%',
  '30.0%',
  '37.8%',
  '25.0%',
  '66.7%',
  '.0%'],
 ['Wildlife', '29', '53', '51', '51', '41', '41', '68', '51', '60', '48'],
 ['',
  '82.8%',
  '84.9%',
  '78.4%',
  '76.5%',
  '87.8%',
  '80.5%',
  '79.4%',
  '82.4%',
  '81.7%',
  '.0%'],
 ['Zoology', '34', '37', '40', '47', '27', '26', '39', '37', '37', '62'],
 ['',
  '76.5%',
  '62.2%',
  '80.0%',
  '63.8%',
  '77.8%',
  '69.2%',
  '74.4%',
  '78.4%',
  '86.5%',
  '.0%']]

In [33]:
# Put the data in a Pandas dataframe and rename columns as needed
table1_df = ....


table1_df

,Anthropology,23,15,18,19,7,13,16,16,8,9
0,Anthropology,23,15,18,19,7,13,16,16,8,9
1,,73.9%,86.7%,83.3%,57.9%,100.0%,76.9%,75.0%,87.5%,87.5%,.0%
2,Applied Fire Science & Mgmt,0,0,0,0,0,2,4,16,15,35
3,,%,%,%,%,%,50.0%,100.0%,56.3%,73.3%,.0%
4,Art,36,36,38,17,20,33,41,41,17,13
...,...,...,...,...,...,...,...,...,...,...,...
129,,39.3%,35.5%,38.0%,50.9%,33.3%,30.0%,37.8%,25.0%,66.7%,.0%
130,Wildlife,29,53,51,51,41,41,68,51,60,48
131,,82.8%,84.9%,78.4%,76.5%,87.8%,80.5%,79.4%,82.4%,81.7%,.0%
132,Zoology,34,37,40,47,27,26,39,37,37,62
133,,76.5%,62.2%,80.0%,63.8%,77.8%,69.2%,74.4%,78.4%,86.5%,.0%

In [35]:
# rename the columns

table1_df.columns = ...

table1_df

,Major Program,Fall 16,Fall 17,Fall 18,Fall 19,Fall 20,Fall 21,Fall 22,Fall 23,Fall 24,Fall 25
0,Anthropology,23,15,18,19,7,13,16,16,8,9
1,,73.9%,86.7%,83.3%,57.9%,100.0%,76.9%,75.0%,87.5%,87.5%,.0%
2,Applied Fire Science & Mgmt,0,0,0,0,0,2,4,16,15,35
3,,%,%,%,%,%,50.0%,100.0%,56.3%,73.3%,.0%
4,Art,36,36,38,17,20,33,41,41,17,13
...,...,...,...,...,...,...,...,...,...,...,...
129,,39.3%,35.5%,38.0%,50.9%,33.3%,30.0%,37.8%,25.0%,66.7%,.0%
130,Wildlife,29,53,51,51,41,41,68,51,60,48
131,,82.8%,84.9%,78.4%,76.5%,87.8%,80.5%,79.4%,82.4%,81.7%,.0%
132,Zoology,34,37,40,47,27,26,39,37,37,62
133,,76.5%,62.2%,80.0%,63.8%,77.8%,69.2%,74.4%,78.4%,86.5%,.0%

In [ ]:
grader.check("q2_3")

**Question 2.4:** Notice that even rows contain numbers and odd rows contain percents in `table1_df1`. Let's separate this into two Pandas data frames. One should contain only numbers, one should contain percents. 

*NOTE:* Make sure that both tables have data in the `Major Program` column. Only the even rows have an entry for `Major Program`!

In [ ]:
# Create numbers data frame
table1_nums = ...
table1_nums

In [ ]:
# Create percents data frame
table1_percents = ...
table1_percents

In [ ]:
grader.check("q2_4")

<!-- BEGIN QUESTION -->

**Question 2.5:** Check the data types of each column in both tables from the previous question.

In [ ]:
# check nums dtypes

In [ ]:
# check percents dtypes

<!-- END QUESTION -->

**Question 2.6:** Cast the datatypes in your tables appropriately. In other words, if a column contains numbers, cast it to an appropriate numeric data type.

*NOTE:* The percents in the `table1_percents` DataFrame should be floats.

In [ ]:
# Cast datatypes in nums table
    
table1_nums.dtypes

In [ ]:
# Cast datatypes in percents table
table1_percents.dtypes

In [ ]:
grader.check("q2_6")

## 3. Visualize

**Question 3.1:** Visualize the relationship between the 1st Year retention rates (percents) in Fall 14 and the 1st Year retention rates (percents) in Fall 23. Make sure your visualization has a title and your axes are labeled appropriately as Fall 14 and Fall 23.

In [ ]:
scatter_16_vs_23 = ...
plt.show()

In [ ]:
grader.check("q3_1")

<!-- BEGIN QUESTION -->

**Question 3.2:** Visualize the trend in 1st Year retention rates (percents) over time for Biology. On the same axes plot the trend for English (in a different color). Make sure your plot has an informative legend, axes labels, and title. 

*HINT:* You will probably find it helpful to reshape your `table1_percents` dataframe. First, use the transpose method: `df.T`...this will get you columns of Year and Biology and English. Then you will need to tidy up the dataframe a little: rename the columns, `.drop('Major Program')` and then reset the index. Lastly, you will use `melt()` to get a long form dataframe with the columns of year/term, Major Program with the levels `Biology` and `English`, and the percent.

In [ ]:
# reshape the data as needed

In [ ]:
# plot the trends
retention_trends = ...
plt.show()

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

**Question 3.3:** Create one more data visualization of your choice. This might require reshaping your data. Describe what insights you gain from your visualization.

In [ ]:
# Visualize

<!-- END QUESTION -->

## You're done! 

Congratulations on finishing the lab! Gus is proud of you! Run the cell below and submit to Canvas. 

<img src="gus_big_stretch.JPG" alt="drawing" width="500"/>

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

In [ ]:
# Save your notebook first, then run this cell to export your submission.
grader.export(run_tests=True)